//! Header parser for MOL files.

use bstr::ByteSlice;
use winnow::error::ErrMode;
use winnow::ModalResult;

use super::utils::next_line;
use crate::ctfile::error::ParseError;

/// Parse the 3-line MOL file header block (name, program info, comment)
///
/// Returns (Vec of 3 strings, updated line offset)
pub(super) fn header_block(
    input: &mut &[u8],
    line_offset: u32,
) -> ModalResult<(Vec<String>, u32), ParseError> {
    let mut headers = Vec::with_capacity(3);

    for index in 0..3 {
        let line = next_line(input).map_err(|_| {
            ErrMode::Cut(ParseError::UnexpectedEof {
                line: line_offset + index,
                block: "header",
            })
        })?;
        let line: &[u8] = line.as_ref();
        headers.push(line.to_str_lossy().into_owned());
    }

    Ok((headers, line_offset + 3))
}

#[cfg(test)]
mod tests {
    use rstest::*;
    use winnow::error::ErrMode;

    use super::*;

    #[rstest]
    #[case::valid(
        b"Caffeine\nRDKit          3D\nGenerated by RDKit\n",
        vec!["Caffeine".to_string(), "RDKit          3D".to_string(), "Generated by RDKit".to_string()]
    )]
    #[case::empty(
        b"\n\n\n",
        vec!["".to_string(), "".to_string(), "".to_string()]
    )]
    #[case::whitespace(
        b"  Molecule Name  \n  Program Info  \n  Comment Line  \n",
        vec!["  Molecule Name  ".to_string(), "  Program Info  ".to_string(), "  Comment Line  ".to_string()]
    )]
    #[case::crlf(
        b"Name\r\nProgram\r\nComment\r\n",
        vec!["Name".to_string(), "Program".to_string(), "Comment".to_string()]
    )]
    fn test_header_block(#[case] input: &[u8], #[case] expected: Vec<String>) {
        let mut remaining = input;
        let (headers, line_offset) = header_block(&mut remaining, 0).unwrap();
        assert!(remaining.is_empty());
        assert_eq!(headers, expected);
        assert_eq!(line_offset, 3);
    }

    #[rstest]
    #[case::two_lines(b"Line1\nLine2\n", ErrMode::Cut(ParseError::UnexpectedEof { line: 2, block: "header" }))]
    fn test_header_block_error(#[case] input: &[u8], #[case] expected_error: ErrMode<ParseError>) {
        let mut remaining = input;
        assert_eq!(header_block(&mut remaining, 0), Err(expected_error));
    }
}
