[package]
name = "umol-params"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords = [
    "chemistry",
    "cheminformatics",
    "molecules",
    "parameters",
    "modeling",
]
description = "Model-dependent parameters for umol."

[lib]
bench = false

[dependencies]
umol-chem = { path = "../umol-chem", version = "0.6.0" }

[dev-dependencies]
rstest = "0.26.1"

[lints.clippy]
absolute_paths = "warn"
mod_module_files = "warn"
