[package]
name = "umol-params"
version = "0.1.0"
authors = ["Dmitrij Rappoport <dmitrij@rappoport.org>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rappoport/umol"
keywords = [
    "chemistry",
    "cheminformatics",
    "computational chemistry",
    "molecular modeling",
    "molecular representation",
]
description = "Model-dependent parameters for umol."

[lib]
bench = false

[dependencies]
umol-shared = { path = "../umol-shared", version = "0.1.0" }

[dev-dependencies]
rstest = "0.26.1"

[lints.clippy]
absolute_paths = "warn"
mod_module_files = "warn"
