//! MOL file writer

use crate::atom::AtomStereoParity;
use crate::bond::{Bond, BondDir, BondStereo, BondType};
use crate::molecule::Molecule;
use crate::Point3D;
use fixed_width::{FixedWidth, WriteError};
use std::io::Write;
use umol::error::DataError;

// --- Fixed Width Structs for Writing --- //

#[derive(Debug, FixedWidth)]
struct MolAtomWriteBlock {
    #[fixed_width(range = 0..10, align = Right, pad = ' ')]
    x: String, // Pre-formatted float
    #[fixed_width(range = 10..20, align = Right, pad = ' ')]
    y: String, // Pre-formatted float
    #[fixed_width(range = 20..30, align = Right, pad = ' ')]
    z: String, // Pre-formatted float
    #[fixed_width(range = 30..31)] // Space separator
    _sep1: String, // Use " "
    #[fixed_width(range = 31..34, align = Left, pad = ' ')]
    element_symbol: String,
    #[fixed_width(range = 34..36, align = Right, pad = ' ')]
    mass_diff: i8,
    #[fixed_width(range = 36..39, align = Right, pad = ' ')]
    charge: u8,
    #[fixed_width(range = 39..42, align = Right, pad = ' ')]
    stereo_parity: u8,
    // TODO: Add H count field if needed
    #[fixed_width(range = 60..63, align = Right, pad = ' ')]
    valence: u8,
    #[fixed_width(range = 66..69, align = Right, pad = ' ')]
    atom_map: u32,
}

#[derive(Debug, FixedWidth)]
struct MolBondWriteBlock {
    #[fixed_width(range = 0..3, align = Right, pad = ' ')]
    atom1_idx: usize,
    #[fixed_width(range = 3..6, align = Right, pad = ' ')]
    atom2_idx: usize,
    #[fixed_width(range = 6..9, align = Right, pad = ' ')]
    bond_type: u8,
    #[fixed_width(range = 9..12, align = Right, pad = ' ')]
    bond_stereo: u8,
    // Skipping topology and reacting center
}

// --- Helper Functions for Writing --- //

fn format_coord(c: f64) -> String {
    format!("{:>10.4f}", c)
}

fn charge_to_code(charge: i8) -> u8 {
    match charge {
        3 => 1,
        2 => 2,
        1 => 3,
        0 => 0,
        -1 => 5,
        -2 => 6,
        -3 => 7,
        _ => 0, // Default to 0 for unmappable charges
    }
}

fn stereo_parity_to_code(parity: Option<AtomStereoParity>) -> u8 {
    match parity {
        Some(AtomStereoParity::Odd) => 1,
        Some(AtomStereoParity::Even) => 2,
        Some(AtomStereoParity::Either) => 3,
        None => 0,
    }
}

fn valence_to_code(valence: Option<u8>) -> u8 {
    match valence {
        None => 0,
        Some(15) => 15,
        Some(v @ 1..=14) => v,
        Some(_) => 0, // Default to 0 for unexpected values
    }
}

fn bond_type_to_code(bt: BondType) -> u8 {
    match bt {
        BondType::Single => 1,
        BondType::Double => 2,
        BondType::Triple => 3,
        BondType::Aromatic => 4,
        BondType::SingleOrDouble => 5,
        BondType::SingleOrAromatic => 6,
        BondType::DoubleOrAromatic => 7,
        BondType::Any => 8,
        BondType::Other => 0,
    }
}

fn bond_stereo_or_dir_to_code(bond: &Bond) -> u8 {
    if bond.bond_type == BondType::Single {
        match bond.dir {
            Some(BondDir::Wedge) => 1,
            Some(BondDir::Dash) => 6,
            None => 0,
        }
    } else if bond.bond_type == BondType::Double {
        match bond.stereo {
            Some(BondStereo::Cis) => 1,
            Some(BondStereo::Trans) => 6,
            Some(BondStereo::Either) => 3,
            None => 0,
        }
    } else {
        0 // Stereo/Dir not applicable for other types
    }
}

// Map fixed_width WriteError to our Result/DataError
fn map_write_error(e: WriteError) -> umol::Error {
    DataError::IoError(std::io::Error::new(std::io::ErrorKind::Other, e)).into()
}

// --- Main Writing Function --- //

pub fn write_mol_v2000(writer: &mut impl Write, molecule: &Molecule) -> Result<()> {
    // --- Header Block ---
    let name = molecule.get_prop("mol_name").map_or("", |s| s.as_str());
    writeln!(writer, "{}", name)?;
    writeln!(writer, "  UMOL      MMDDYYHHMM")?; // Placeholder info
    writeln!(writer, "Generated by umol")?;

    // --- Counts Line ---
    let atom_count = molecule.atom_count();
    let bond_count = molecule.bond_count();

    // Refined Chiral Flag Calculation
    let mut is_chiral = molecule.conformers().first().map_or(false, |c| c.is_3d);
    if !is_chiral {
        for node_idx in molecule.graph.node_indices() {
            if let Some(atom) = molecule.atom(node_idx) {
                if atom.stereo_parity.is_some() {
                    is_chiral = true;
                    break;
                }
            }
        }
    }
    if !is_chiral {
        for edge_idx in molecule.graph.edge_indices() {
            if let Some(bond) = molecule.bond(edge_idx) {
                if bond.stereo.is_some() || bond.dir.is_some() {
                    is_chiral = true;
                    break;
                }
            }
        }
    }
    let chiral_flag = if is_chiral { 1 } else { 0 };

    writeln!(
        writer,
        "{:>3}{:>3}  0  0  {}  0  0  0  0  0999 V2000",
        atom_count, bond_count, chiral_flag
    )?;

    // --- Atom Block ---
    let conformer = molecule.conformers().first();

    // Ensure atoms are written in MOL index order
    let mut sorted_indices: Vec<(usize, AtomIndex)> = molecule
        .internal_indices
        .iter()
        .map(|(&graph_idx, &mol_idx)| (mol_idx, graph_idx))
        .collect();
    sorted_indices.sort_unstable_by_key(|&(mol_idx, _)| mol_idx);

    for (_mol_idx, graph_index) in sorted_indices {
        let atom = molecule
            .atom(graph_index)
            .expect("Graph index from map must be valid");
        let pos = conformer
            .and_then(|c| c.get_position(graph_index))
            .unwrap_or(&Point3D::origin()); // Default to origin if no conformer/position

        let atom_block = MolAtomWriteBlock {
            x: format_coord(pos.x),
            y: format_coord(pos.y),
            z: format_coord(pos.z),
            _sep1: " ".to_string(),
            element_symbol: atom.element.symbol().to_string(),
            // Use mass_difference directly
            mass_diff: atom.mass_difference.unwrap_or(0),
            charge: charge_to_code(atom.formal_charge),
            stereo_parity: stereo_parity_to_code(atom.stereo_parity),
            // Map valence correctly
            valence: valence_to_code(atom.valence),
            atom_map: atom.atom_map_num.unwrap_or(0),
        };

        let line_str = fixed_width::to_string(&atom_block).map_err(map_write_error)?;
        writeln!(writer, "{}", line_str)?;
    }

    // --- Bond Block ---
    for edge_ref in molecule.graph.edge_references() {
        let bond = edge_ref.weight();
        let graph_idx1 = edge_ref.source();
        let graph_idx2 = edge_ref.target();

        // Map back to MOL indices
        let mol_idx1 = *molecule
            .internal_indices
            .get(&graph_idx1)
            .expect("Mapping missing for source atom");
        let mol_idx2 = *molecule
            .internal_indices
            .get(&graph_idx2)
            .expect("Mapping missing for target atom");

        let bond_block = MolBondWriteBlock {
            atom1_idx: mol_idx1,
            atom2_idx: mol_idx2,
            // Use updated helper
            bond_type: bond_type_to_code(bond.bond_type),
            bond_stereo: bond_stereo_or_dir_to_code(bond),
        };

        let line_str = fixed_width::to_string(&bond_block).map_err(map_write_error)?;
        writeln!(writer, "{}", line_str)?;
    }

    // --- Properties Block (M lines) ---
    let mut charges_to_write: Vec<(usize, i8)> = Vec::new();
    let mut isotopes_to_write: Vec<(usize, u16)> = Vec::new(); // Store absolute mass as u16
    let mut radicals_to_write: Vec<(usize, u8)> = Vec::new();

    // Collect non-default properties (iterate in MOL index order)
    let mut sorted_indices_m: Vec<(usize, AtomIndex)> = molecule
        .internal_indices
        .iter()
        .map(|(&graph_idx, &mol_idx)| (mol_idx, graph_idx))
        .collect();
    sorted_indices_m.sort_unstable_by_key(|&(mol_idx, _)| mol_idx);

    for (mol_idx, graph_index) in sorted_indices_m {
        let atom = molecule
            .atom(graph_index)
            .expect("Graph index from map must be valid");
        if atom.formal_charge != 0 {
            charges_to_write.push((mol_idx, atom.formal_charge));
        }

        // Refined isotope collection
        if let Some(diff) = atom.mass_difference {
            if diff != 0 {
                // Only calculate/write if non-zero difference
                let standard_mass = atom.element.default_mass().unwrap_or(0.0);
                let iso_mass_f64 = (standard_mass + diff as f64).round();
                if iso_mass_f64 >= 0.0 && iso_mass_f64 <= u16::MAX as f64 {
                    isotopes_to_write.push((mol_idx, iso_mass_f64 as u16));
                } else {
                    eprintln!("Warning: Calculated invalid absolute isotope mass ({}) for atom {}, skipping M ISO write.", iso_mass_f64, mol_idx);
                }
            }
            // If diff is 0, we don't write anything (it's the default)
        }

        // Check radical field
        if let Some(rad_code @ (1 | 2 | 3)) = atom.radical {
            radicals_to_write.push((mol_idx, rad_code));
        }
    }

    // Write M CHG lines (max 8 pairs per line)
    for chunk in charges_to_write.chunks(8) {
        write!(writer, "M  CHG{:>3}", chunk.len())?;
        for (mol_idx, charge) in chunk {
            write!(writer, " {:>3}{:>4}", mol_idx, charge)?;
        }
        writeln!(writer)?;
    }

    // Write M ISO lines (max 8 pairs per line) - writing absolute mass (u16)
    for chunk in isotopes_to_write.chunks(8) {
        write!(writer, "M  ISO{:>3}", chunk.len())?;
        for (mol_idx, iso_mass) in chunk {
            // iso_mass is u16
            write!(writer, " {:>3}{:>4}", mol_idx, iso_mass)?; // Write u16
        }
        writeln!(writer)?;
    }

    // Write M RAD lines (max 8 pairs per line)
    for chunk in radicals_to_write.chunks(8) {
        write!(writer, "M  RAD{:>3}", chunk.len())?;
        for (mol_idx, rad_code) in chunk {
            write!(writer, " {:>3}{:>4}", mol_idx, rad_code)?;
        }
        writeln!(writer)?;
    }

    // --- End Line ---
    writeln!(writer, "M  END")?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*; // Import functions from parent module
    use crate::atom::Atom;
    use crate::bond::{Bond, BondType};
    use crate::conformer::Conformer;
    use crate::molecule::Molecule;
    use crate::types::Point3D;
    use std::io::Cursor;
    use umol_data::element::periodic_table;

    #[test]
    fn test_write_basic() {
        // Manually construct Ethanol
        let mut molecule = Molecule::new();
        molecule.set_prop("mol_name".to_string(), "Ethanol - Written".to_string());

        let c1 = molecule.add_atom(1, Atom::new(periodic_table().get_by_symbol("C").unwrap()));
        let c2 = molecule.add_atom(2, Atom::new(periodic_table().get_by_symbol("C").unwrap()));
        let o3 = molecule.add_atom(3, Atom::new(periodic_table().get_by_symbol("O").unwrap()));
        let h4 = molecule.add_atom(4, Atom::new(periodic_table().get_by_symbol("H").unwrap()));
        let h5 = molecule.add_atom(5, Atom::new(periodic_table().get_by_symbol("H").unwrap()));
        let h6 = molecule.add_atom(6, Atom::new(periodic_table().get_by_symbol("H").unwrap()));
        let h7 = molecule.add_atom(7, Atom::new(periodic_table().get_by_symbol("H").unwrap()));
        let h8 = molecule.add_atom(8, Atom::new(periodic_table().get_by_symbol("H").unwrap()));
        let h9 = molecule.add_atom(9, Atom::new(periodic_table().get_by_symbol("H").unwrap()));

        molecule
            .add_bond(1, 2, Bond::new(BondType::Single))
            .unwrap();
        molecule
            .add_bond(2, 3, Bond::new(BondType::Single))
            .unwrap();
        molecule
            .add_bond(1, 4, Bond::new(BondType::Single))
            .unwrap();
        molecule
            .add_bond(1, 5, Bond::new(BondType::Single))
            .unwrap();
        molecule
            .add_bond(1, 6, Bond::new(BondType::Single))
            .unwrap();
        molecule
            .add_bond(2, 7, Bond::new(BondType::Single))
            .unwrap();
        molecule
            .add_bond(2, 8, Bond::new(BondType::Single))
            .unwrap();
        molecule
            .add_bond(3, 9, Bond::new(BondType::Single))
            .unwrap();

        // Add charge/isotope for M line testing
        molecule.atom_mut(o3).unwrap().formal_charge = -1;
        molecule.atom_mut(c1).unwrap().isotope = 13;

        // Add conformer
        let mut conf = Conformer::new(molecule.atom_count(), true);
        conf.set_position(c1, Point3D::new(1.0, 0.0, 0.0));
        conf.set_position(c2, Point3D::new(2.0, 0.0, 0.0));
        conf.set_position(o3, Point3D::new(3.0, 0.0, 0.0));
        // ... set other positions if needed for full check
        molecule.add_conformer(conf).unwrap();

        let mut buffer: Vec<u8> = Vec::new();
        let result = write_mol_v2000(&mut buffer, &molecule);

        assert!(result.is_ok());
        let output_mol = String::from_utf8(buffer).expect("Invalid UTF-8 in output");
        println!("Written MOL:\n{}", output_mol); // Print for debugging

        // Basic substring checks
        assert!(output_mol.starts_with("Ethanol - Written"));
        assert!(output_mol.contains("  9  8  0  0  1  0  0  0  0  0999 V2000")); // Check counts & chiral flag
        assert!(output_mol.contains("  1.0000    0.0000    0.0000 C   ")); // Check atom formatting
        assert!(output_mol.contains("  1  2  1  0")); // Check bond formatting
        assert!(output_mol.contains("M  CHG  1   3  -1")); // Check M CHG line
        assert!(output_mol.contains("M  ISO  1   1  13")); // Check M ISO line
        assert!(output_mol.ends_with("M  END\n"));
    }
}
