[workspace]
members = [
    "umol-graph-ir",
    "umol-graph-ir-macros",
    "umol-chem",
    "umol-coordgen-sys",
    "umol-utils",
    "umol-edn",
    "umol-edn-macros",
    "umol-geometric",
    "umol-geometric-core",
    "umol-geometric-graph",
    "umol-graph",
    "umol-graph-core",
    "umol-io",
    "umol-msym",
    "umol-msym-sys",
    "umol-nauty-sys",
    "umol-params",
    "umol-perm",
    "umol-py",
]
exclude = ["umol-graph-ir/fuzz", "umol-edn/fuzz", "umol-io/fuzz"]
resolver = "2"

[workspace.package]
version = "0.7.0"
authors = ["Dmitrij Rappoport <dmitrij@rappoport.org>"]
edition = "2021"
rust-version = "1.87"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dayhofflabs/umol"
readme = "README.md"

[workspace.dependencies]
cc = "1.2.60"

[profile.bench]
debug = true

[profile.profiling]
inherits = "release"
debug = 1
