[package]
name = "umol-macros"
version = "0.1.0"
authors = ["Dmitrij Rappoport <dmitrij@rappoport.org>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rappoport/umol"
keywords = [
    "chemistry",
    "cheminformatics",
    "computational chemistry",
    "molecular modeling",
    "molecular representation",
]
description = "Procedural macros for umol."

[lib]
proc-macro = true
bench = false

[dependencies]
heck = "0.5.0"
proc-macro2 = "1.0.101"
quote = "1.0.40"
syn = { version = "~1.0", features = ["full", "extra-traits"] }
