[package]
name = "umol-geometric"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords = [
    "chemistry",
    "cheminformatics",
    "molecules",
    "geometry",
    "symmetry",
]
description = "3D geometric molecular models for umol."
edition.workspace = true
rust-version.workspace = true

[lib]
bench = false

[dependencies]
nalgebra = "0.34.0"
nom = { version = "8.0.0" }
num = "0.4.3"
num-traits = "0.2.19"
umol-chem = { path = "../umol-chem", version = "0.6.0" }
umol-msym = { path = "../umol-msym", version = "0.6.0" }
umol-params = { path = "../umol-params", version = "0.6.0" }

[dev-dependencies]
criterion = "0.8.1"
float-cmp = "0.10.0"
insta = { version = "1.43.2", features = ["yaml", "glob"] }
pretty_assertions = "1.4.1"
rstest = "0.26.1"
serde = { version = "1", features = ["derive"] }

[lints.clippy]
absolute_paths = "warn"
mod_module_files = "warn"
