[H]
0 = [
    "H #v", # HX, H2
    "H #u", # H atom, s1
]
1 = [
    "H #c+", # H+
]
-1 = [
    "H #c- #n", # H-
]

[He]
0 = [
    "He", # He atom, s0
]

[Li]
0 = [
    "Li #v", # LiX, Li2
    "Li #u", # Li atom, s1
]
1 = [
    "Li #c+", # Li+
]

[Be]
0 = [
    "Be #n", # Be atom, s2
]
2 = [
    "Be #c+2", # Be2+
]

[B]
0 = [
    "B #v3",        # BX3, BH3
    "B #v2 #h",     # BX2H
    "B #v1 #h2",    # BXH2
    "B #h3",        # BH3
    "B #u1 #v2",    # BX2, BH2, BO
    "B #u1 #v #h",  # BXH
    "B #u1 #h2",    # BH2
    "B #n1 #v",     # BX, BH, BF
    "B #n1 #u",     # B atom, s2p1
    "B #v3 #a0",    # neutral aromatic B with substituent: borepin BR, boroxine BR3, 1-substituted 1,2-azaborine
    "B #v2 #a0 #h", # neutral aromatic B with H: borazine BH, 1,2-azaborine BH, borepin BH
]
-1 = [
    "B #c- #v4",        # [BX4]-, BO2-
    "B #c- #v3 #h",     # BX3H-
    "B #c- #v2 #h2",    # [BX2H2]-
    "B #c- #v #h3",     # [BXH3]-
    "B #c- #h4",        # [BH4]-
    "B #c- #n #v2",     # [BX2]-, BO-, [B-][N+]
    "B #c- #n #v #h",   # BXH-
    "B #c- #n #h2",     # [BH2]-
    "B #c- #v2 #a #h",  # [C5H5BH]-, boratabenzene anion (1H)
    "B #c- #v3 #a",     # [C5H5BR]-, boratabenzene anion (R-substituted)
    "B #c- #v3 #a2",    # borolide dianion BR (1-substituted 5-ring), localized
    "B #c- #v2 #a2 #h", # borolide dianion BH
]

[C]
0 = [
    "C #v4",       # CX4, CH4
    "C #v3 #h",    # CX3H
    "C #v2 #h2",   # CX2H2
    "C #v #h3",    # CXH3
    "C #h4",       # CH4
    "C #v3 #a",    # C6H5X, C6H6
    "C #v2 #a #h", # C6H6
    "C #u #v3",    # CX3, CH3
    "C #u #v2 #h", # CX2H
    "C #u #v #h2", # CXH2
    "C #u #h3",    # CH3
    "C #u2 #v2",   # CX2, CH2 (triplet)
    "C #u2 #v #h", # CXH (triplet)
    "C #u2 #h2",   # CH2 (triplet)
    "C #n #v2",    # CX2, CH2 (singlet)
    "C #n #v #h",  # CXH (singlet)
    "C #n #h2",    # CH2 (singlet)
    "C #n #u #v",  # CX, CH (doublet)
    "C #n #u #h",  # CH (doublet)
    "C #u3 #v",    # CX, CH (quartet)
    "C #u3 #h",    # CH (quartet)
    "C #n #u2",    # C atom, s2p2
]
1 = [
    "C #c+ #v3",        # [CX3]+, [CH3]+, [C-][O+]
    "C #c+ #v2 #h",     # CX2H+
    "C #c+ #v #h2",     # [CXH2]+
    "C #c+ #v3 #a0",    # C7H6X+
    "C #c+ #v2 #a0 #h", # [C7H7]+
    "C #c+ #h3",        # [CH3]+
]
-1 = [
    "C #c- #n #v3",     # [CX3]-, CN-
    "C #c- #n #v2 #h",  # CX2H-
    "C #c- #n #v #h2",  # [XCH2]-
    "C #c- #n #h3",     # [CH3]-
    "C #c- #v3 #a2",    # C5H4X-
    "C #c- #v2 #a2 #h", # [C5H5]-
]

[N]
0 = [
    "N #n #v3",      # N2, NH3, NX3, HONO, N2O3, HN=NH, H2N-NH2
    "N #n #v2 #h",   # NX2H
    "N #n #v #h2",   # NXH2
    "N #n #h3",      # NH3
    "N #n #v2 #a",   # C5H5N
    "N #v3 #a2",     # C4H4NX, C4H4NH
    "N #v2 #a2 #h",  # C4H4NH
    "N #n #u #v2",   # NX2, NH2, NO
    "N #n #u #v #h", # NXH
    "N #n #u #h2",   # NH2
    "N #n2 #v",      # NX, NH
    "N #n2 #h",      # NH
    "N #n #u3",      # N atom, s2p3
]
1 = [
    "N #c+ #v4",       # [NX4]+, [NH4]+, [NO2]+, HONO2
    "N #c+ #v3 #h",    # [NX3H]+
    "N #c+ #v2 #h2",   # [NX2H2]+
    "N #c+ #v #h3",    # [NXH3]+
    "N #c+ #h4",       # [NH4]+
    "N #c+ #v3 #a",    # C5H5N(+)X, C5H5N(+)H
    "N #c+ #v2 #a #h", # C5H5N(+)H
    "N #c+ #u #v3",    # O=N(+)^-O-
    "N #c+ #n #v2",    # [NX2]+, [NH2]+, NO+
    "N #c+ #n #v #h",  # NXH+
    "N #c+ #n #h2",    # [NH2]+
]
-1 = [
    "N #c- #n2 #v2",   # [NX2]-, [NH2]-
    "N #c- #n2 #v #h", # NXH-
    "N #c- #n2 #h2",   # [NH2]-
]
-3 = [
    "N #c-3 #n4", # N3-
]

[O]
0 = [
    "O #n2 #v2",    # O2, OH2, OX2
    "O #n2 #v #h",  # OXH
    "O #n2 #h2",    # OH2
    "O #n #v2 #a2", # C4H4O
    "O #n2 #u #v",  # OH, OX
    "O #n2 #u #h",  # OH
    "O #n2 #u2",    # O atom, s2p4
]
1 = [
    "O #c+ #n #v3",    # [OX3]+, [OH3]+
    "O #c+ #n #v2 #h", # [OXH2]+
    "O #c+ #n #v #h2", # [OXH2]+
    "O #c+ #n #h3",    # [OH3]+
    "O #c+ #n #v2 #a", # C5H5O+
    "O #c+ #n2 #v",    # OX+, OH+
    "O #c+ #n #h3",    # OH+
]
-1 = [
    "O #c- #n3 #v", # OX-, OH-
    "O #c- #n3 #h", # OH-
]
-2 = [
    "O #c-2 #n4", # O2-
]

[F]
0 = [
    "F #n3 #v", # F2, HF, FX
    "F #n3 #h", # HF
    "F #n3 #u", # F atom, s2p5
]
-1 = [
    "F #c- #n4", # F-
]

[Ne]
0 = [
    "Ne", # Ne atom, s0
]

[Na]
0 = [
    "Na #u", # Na atom, s1
]
1 = [
    "Na #c+", # Na+
]

[Mg]
0 = [
    "Mg #v2",
    "Mg #u #v",
    "Mg #n",    # Mg atom, s2
]
2 = [
    "Mg #c+2", # Mg2+
]

[Al]
0 = [
    "Al #v3",
    "Al #n #u", # Al atom, s2p1
]
3 = [
    "Al #c+3", # Al3+
]

[Si]
0 = [
    "Si #v4",     # SiH4, SiX4
    "Si #v3 #h",  # SiX2H
    "Si #v2 #h2", # SiX2H2
    "Si #v #h3",  # SiXH3
    "Si #h4",     # SiH4
    "Si #u #v3",  # SiX3
    "Si #n #v2",  # SiX2 (singlet)
    "Si #u2 #v2", # SiX2 (triplet)
    "Si #n #u2",  # Si atom, s2p2
]
1 = [
    "Si #c+ #v3", # [SiX3]+
]
-1 = [
    "Si #c- #n #v3", # [SiX3]-
]

[P]
0 = [
    "P #n #v3",      # PH3, P2, XP3
    "P #n #v2 #h",   # PX2H
    "P #n #v #h2",   # PXH2
    "P #n #h3",      # PH3
    "P #n #u #v2",   # PX2, PH2
    "P #n #u #v #h", # PXH
    "P #n #u #h2",   # PXH2
    "P #v5",
    "P #n #u3",      # P atom, s2p3
]
1 = [
    "P #c+ #v4",      # [PX4]+
    "P #c+ #v3 #h",   # [PXH3]+
    "P #c+ #v2 #h2",  # [PX2H2]+
    "P #c+ #v #h3",   # [PXH3]+
    "P #c+ #h4",      # [PH4]+
    "P #c+ #n #v2",   # [PX2]+, [PH2]+
    "P #c+ #n #v #h", # PXH+
    "P #c+ #n #h2",   # [PH2]+
]
-1 = [
    "P #c- #n2 #v2",   # [PX2]-
    "P #c- #n2 #v #h", # PXH-
    "P #c- #n2 #h2",   # [PH2]-
]
-3 = [
    "P #c-3 #n4", # P3-
]

[S]
0 = [
    "S #n2 #v2",     # SH2, S8, SX2, H2S2
    "S #n2 #v #h",   # SXH, H2S2
    "S #n2 #h2",     # SH2
    "S #n1 #v2 #a2", # C4H4S
    "S #n2 #u #v1",  # SX, SH
    "S #n2 #u #h",   # SH
    "S #n1 #v4",
    "S #v6",
    "S #n2 #u2",     # S atom, s2p4
]
1 = [
    "S #c+ #n #v3",     # [SX3]+, [SH3]+
    "S #c+ #n #v2 #h",  # [SX2H]+
    "S #c+ #n #v1 #h2", # [SXH2]+
    "S #c+ #n #h3",     # [SH3]+
    "S #c+ #n #v2 #a",  # C5H5S+
]
-1 = [
    "S #c- #n3 #v", # SX-, SH-
    "S #c- #n3 #h", # SH-
]
-2 = [
    "S #c-2 #n4", # S2-
]

[Cl]
0 = [
    "Cl #n3 #v",     # ClH, ClX, HOCl
    "Cl #n3 #h",     # ClH
    "Cl #n2 #v3",    # ClF3, HOClO
    "Cl #n1 #u #v4", # ClO2
    "Cl #n1 #v5",    # ClF5, HOClO2
    "Cl #u1 #v6",    # ClO3
    "Cl #v7",        # HOClO3
    "Cl #n3 #u1",    # Cl atom, s2p5
]
1 = [
    "Cl #c+ #n3",     # Cl+
    "Cl #c+ #n2 #v2", # Cl-Cl(+)-Cl (DOI: 10.1021/ic950305s)
]
-1 = [
    "Cl #c- #n4", # Cl-
]

[Ar]
0 = [
    "Ar", # Ar atom, s0
]

[K]
0 = [
    "K #u", # K atom, s1
]
1 = [
    "K #c+", # K+
]

[Ca]
0 = [
    "Ca #n", # Ca atom, s2
]
2 = [
    "Ca #c+2", # Ca2+
]

[Sc]
0 = [
    "Sc #n #u", # Sc atom, s2d1
]
3 = [
    "Sc #c+3", # Sc3+, d0
]

[Ti]
0 = [
    "Ti #n #u2", # Ti atom, s2d2
]
3 = [
    "Ti #c+3 #u", # Ti3+, d1
]
4 = [
    "Ti #c+4", # Ti4+, d0
]

[V]
0 = [
    "V #n #u3", # V atom, s2d3
]
2 = [
    "V #c+2 #u3", #  #v2+, d3
]
3 = [
    "V #c+3 #u2", #  #v3+, d2
]

[Cr]
0 = [
    "Cr #u6", # Cr atom, s1d5
]
2 = [
    "Cr #c+2 #u4",    # Cr2+, d4 high-spin
    "Cr #c+2 #n #u2", # Cr2+, d4 low-spin
]
3 = [
    "Cr #c+3 #u3", # Cr3+, d3
]

[Mn]
0 = [
    "Mn #n #u5", # Mn atom, s2d5
]
2 = [
    "Mn #c+2 #u5",    # Mn2+, d5 high-spin
    "Mn #c+2 #n2 #u", # Mn2+, d5 low-spin

]
3 = [
    "Mn #c+3 #u4",    # Mn3+, d4 high-spin
    "Mn #c+3 #n #u2", # Mn3+, d4 low-spin
]

[Fe]
0 = [
    "Fe #n2 #u4", # Fe atom, s2d6
]
2 = [
    "Fe #c+2 #n #u4",  # Fe2+, d6 high-spin
    "Fe #c+2 #n2 #u2", # Fe2+, d6 intermediate-spin
    "Fe #c+2 #n3",     # Fe2+, d6 low-spin
]
3 = [
    "Fe #c+3 #u5",     # Fe3+, d5 high-spin
    "Fe #c+3 #n1 #u3", # Fe3+, d5 intermediate-spin
    "Fe #c+3 #n2 #u1", # Fe3+, d5 low-spin
]

[Co]
0 = [
    "Co #n3 #u3", # Co atom, s2d7
]
2 = [
    "Co #c+2 #n2 #u3", # Co2+, d7 high-spin
    "Co #c+2 #n3 #u",  # Co2+, d7 low-spin
]
3 = [
    "Co #c+3 #n3",    # Co3+, d6 low-spin
    "Co #c+3 #n #u4", # Co3+, d6 high-spin
]

[Ni]
0 = [
    "Ni #n4 #u2", # Ni atom, s2d8
]
2 = [
    "Ni #c+2 #n3 #u2", # Ni2+, d8 high-spin
    "Ni #c+2 #n4",     # Ni2+, d8 low-spin
]

[Cu]
0 = [
    "Cu #n5 #u", # Cu atom, s1d10
]
1 = [
    "Cu #c+ #n5", # Cu+, d10
]
2 = [
    "Cu #c+2 #n4 #u", # Cu2+, d9
]

[Zn]
0 = [
    "Zn #n", # Zn atom, s2
]
2 = [
    "Zn #c+2", # Zn2+, s0
]

[Ga]
0 = [
    "Ga #n #u", # Ga atom, s2p1
]
3 = [
    "Ga #c+3", # Ga3+
]

[Ge]
0 = [
    "Ge #n #u2", # Ge atom, s2p2
]

[As]
0 = [
    "As #n #u3",     # As atom, s2p3
    "As #n #v3",     # AsX3
    "As #n #v2 #h",  # AsX2H
    "As #n #v #h2",  # AsXH2
    "As #n #h3",     # AsH3
    "As #n #u #v2",  # AsX2
    "As #v3 #a2",    # C4H4AsX, C4H4AsH
    "As #v2 #a2 #h", # C4H4AsH
    "As #n #v2 #a",  # C5H5As
]
1 = [
    "As #c+ #v4", # [AsX4]+
]
-1 = [
    "As #c- #n2 #v2", # [AsX2]-
]
-3 = [
    "As #c-3 #n4", # As3-
]

[Se]
0 = [
    "Se #n2 #v2",     # SeH2, Sen, SeX2
    "Se #n2 #v #h",   # SeXH
    "Se #n2 #h2",     # SeH2
    "Se #n1 #v2 #a2", # C4H4Se
    "Se #n2 #u #v",   # SeX, SeH
    "Se #n2 #u #h",   # SeH
    "Se #n #v4",
    "Se #v6",
    "Se #n2 #u2",     # Se atom, s2p4
]
1 = [
    "Se #c+ #n #v3",    # [SeX3]+, [H3Se]+
    "Se #c+ #n #v2 #h", # [SeX2H]+
    "Se #c+ #n #v #h2", # [SeXH2]+
    "Se #c+ #n #h3",    # [H3Se]+
]
-1 = [
    "Se #c- #n3 #v", # SeX-
    "Se #c- #n3 #h", # SeH-
]
-2 = [
    "Se #c-2 #n4", # Se2-
]

[Br]
0 = [
    "Br #n3 #v",  # Br2, HBr, BrX, HOBr
    "Br #n3 #h",  # BrH
    "Br #n2 #v3", # BrF3, HOBrO
    "Br #n #v5",  # BrF5, HOBrO2
    "Br #v7",     # HOBrO3
    "Br #n3 #u",  # Br atom, s2p5
]
1 = [
    "Br #c+ #n3",     # Br+
    "Br #c+ #n2 #v2", # Br-Br(+)-Br, X-Br(+)-X  (DOI: 10.1021/ic950305s)
]
-1 = [
    "Br #c- #n4", # Br-
]

[Kr]
0 = [
    "Kr #n4",     # Kr atom, s2p6
    "Kr #n3 #m2", # KrF2
]
1 = [
    "Kr #c+ #n3 #v",    # KrF+
    "Kr #c+ #n3 #r #v", # FKrF->KrF+, HCN->KrF
]

[Rb]
0 = [
    "Rb #u", # Rb atom, s1
]
1 = [
    "Rb #c+", # Rb+
]

[Sr]
0 = [
    "Sr #n", # Sr atom, s2
]
2 = [
    "Sr #c+2", # Sr2+
]

[Y]
0 = [
    "Y #n #u", # Y atom, s1d1
]
3 = [
    "Y #c+3", # Y3+, d0
]

[Zr]
0 = [
    "Zr #n #u2", # Zr atom, s2d2
]
4 = [
    "Zr #c+4", # Zr4+, d0
]

[Nb]
0 = [
    "Nb #u5", # Nb atom, s1d4
]
3 = [
    "Nb #c+3 #u2", # Nb3+, d2
]

[Mo]
0 = [
    "Mo #u6", # Mo atom, s1d5
]
2 = [
    "Mo #c+2 #u4",     # Mo2+, d4 high-spin
    "Mo #c+2 #n1 #u2", # Mo2+, d4 low-spin
]
3 = [
    "Mo #c+3 #u3", # Mo3+, d3
]

[Tc]
0 = [
    "Tc #n1 #u5", # Tc atom, s2d5
]

[Ru]
0 = [
    "Ru #n2 #u4", # Ru atom, s1d7
]
2 = [
    "Ru #c+2 #n3", # Ru2+, d6 low-spin
]
3 = [
    "Ru #c+3 #n2 #u", # Ru3+, d5 low-spin
]

[Rh]
0 = [
    "Rh #n3 #u3", # Rh atom, s1d8
]
2 = [
    "Rh #c+2 #n3 #u", # Rh2+, d7 low-spin
]
3 = [
    "Rh #c+3 #n3", # Rh3+, d6 low-spin
]

[Pd]
0 = [
    "Pd #n5", # Pd atom, d10
]
2 = [
    "Pd #c+2 #n4", # Pd2+ d8 low-spin
]

[Ag]
0 = [
    "Ag #n5 #u", # Ag atom, s1d10
]
1 = [
    "Ag #c+ #n5", # Ag+, d10
]
2 = [
    "Ag #c+2 #n4 #u", # Ag2+, d9
]

[Cd]
0 = [
    "Cd #n", # Cd atom, s2
]
2 = [
    "Cd #c+2", # Cd2+, s0
]

[In]
0 = [
    "In #n #u", # In atom, s2p1
]
3 = [
    "In #c+3", # In3+
]

[Sn]
0 = [
    "Sn #n #u2", # Sn atom, s2p2
]

[Sb]
0 = [
    "Sb #n #u3",    # Sb atom, s2p3
    "Sb #n #v3",    # SbX3
    "Sb #n #v2 #h", # SbX2H
    "Sb #n #v #h2", # SbXH2
    "Sb #n #h3",    # SbH3
    "Sb #n #u #v2", # SbX2
]
1 = [
    "Sb #c+ #v4", # [SbX4]+
]
-1 = [
    "Sb #c- #n2 #v2", # [SbX2]-
]
-3 = [
    "Sb #c-3 #n4", # Sb3-
]

[Te]
0 = [
    "Te #n2 #u2",   # Te atom, s2p4
    "Te #n2 #v2",   # TeH2, Ten, TeX2
    "Te #n2 #v #h", # TeXH
    "Te #n2 #h2",   # TeH2
    "Te #n2 #u #v", # TeX
]
-1 = [
    "Te #c- #n3 #v", # TeX-
]
1 = [
    "Te #c+ #n #v3", # [TeX3]+
]
-2 = [
    "Te #c-2 #n4", # Te2-
]

[I]
0 = [
    "I #n3 #v",  # I2, IX, IH, HOI
    "I #n3 #h",  # IH
    "I #n2 #v3", # IF3, HOIO
    "I #n #v5",  # IF5, HOIO2
    "I #v7",     # IF7, HOIO3
    "I #n3 #u",  # I atom, s2p5
]
1 = [
    "I #c+ #n3",     # I+
    "I #c+ #n2 #v2", # I-I(+)-I, X-I(+)-X  (DOI: 10.1021/ic950305s)
]
-1 = [
    "I #c- #n4", # I-
]

[Xe]
0 = [
    "Xe #n3 #m2",   # XeF2, XeCl2, XeX2
    "Xe #n2 #m4",   # XeF4, XeOF2
    "Xe #n #m6",    # XeF6, XeOF4, XeO2F2, [HXeO4]-, [XeO3F]-
    "Xe #n #r #m6", # MeCN->XeO3
    "Xe #m8",       # XeO2F4, XeO3F2, XeO4, H4XeO6, [XeO6]3-, [XeO6]4-
    "Xe #n4",       # Xe atom, s2p6
]
1 = [
    "Xe #c+ #n3 #v",       # XeF+, XeCl+, XeX+
    "Xe #c+ #n3 #r #v",    # HF->XeF+, HCN->XeF+, MeCN->XeF+
    "Xe #c+ #n2 #v #m2",   # [XeF3]+, [XeF2X]+
    "Xe #c+ #n #v #m4",    # [XeF5]+, [XeOF3]+, XeO2F+
    "Xe #c+ #n #r #v #m4", # F5XeF->[XeF5]+
]
-1 = [
    "Xe #c- #n2 #v #m4", # [XeF5]-
    "Xe #c- #n #v #m6",  # [XeF7]-, [XeO2F3]-, [XeOF5]-
]
-2 = [
    "Xe #c-2 #n #v2 #m6", # [XeF8]2-
]

[Cs]
0 = [
    "Cs #u", # Cs atom, s1
]
1 = [
    "Cs #c+", # Cs+
]

[Ba]
0 = [
    "Ba #n", # Ba atom, s2
]
2 = [
    "Ba #c+2", # Ba2+
]

[La]
0 = [
    "La #n #u", # La atom, s2d1
]
3 = [
    "La #c+3", # La3+
]

[Ce]
0 = [
    "Ce #n #u2 #s", # Ce atom, s2d1f1
]
3 = [
    "Ce #c+3 #u", # Ce3+, f1
]
4 = [
    "Ce #c+4", # Ce4+
]

[Pr]
0 = [
    "Pr #n #u3", # Pr atom, s2f3
]
3 = [
    "Pr #c+3 #u2", # Pr3+, f2
]
4 = [
    "Pr #c+4 #u1", # Pr4+, f1
]

[Nd]
0 = [
    "Nd #n #u4", # Nd atom, s2f4
]
3 = [
    "Nd #c+3 #u3", # Nd3+, f3
]

[Pm]
0 = [
    "Pm #n #u5", # Pm atom, s2f5
]
3 = [
    "Pm #c+3 #u4", # Pm3+, f4
]

[Sm]
0 = [
    "Sm #n #u6", # Sm atom, s2f6
]
2 = [
    "Sm #c+2 #u6", # Sm2+, f6
]
3 = [
    "Sm #c+3 #u5", # Sm3+, f5
]

[Eu]
0 = [
    "Eu #n #u7", # Eu atom, s2f7
]
2 = [
    "Eu #c+2 #u7", # Eu2+, f7
]
3 = [
    "Eu #c+3 #u6", # Eu3+, f6
]

[Gd]
0 = [
    "Gd #n #u8", # Gd atom, s2d1f7
]
3 = [
    "Gd #c+3 #u7", # Gd3+, f7
]

[Tb]
0 = [
    "Tb #n3 #u5", # Tb atom, s2f9
]
3 = [
    "Tb #c+3 #n #u6", # Tb3+, f8
]
4 = [
    "Tb #c+4 #u7", # Tb4+, f7
]

[Dy]
0 = [
    "Dy #n4 #u4", # Dy atom, s2f10
]
3 = [
    "Dy #c+3 #n2 #u5", # Dy3+, f9
]

[Ho]
0 = [
    "Ho #n5 #u3", # Ho atom, s2f11
]
3 = [
    "Ho #c+3 #n3 #u4", # Ho3+, f10
]

[Er]
0 = [
    "Er #n6 #u2", # Er atom, s2f12
]
3 = [
    "Er #c+3 #n4 #u3", # Er3+, f11
]

[Tm]
0 = [
    "Tm #n7 #u", # Tm atom, s2f13
]
3 = [
    "Tm #c+3 #n5 #u2", # Tm3+, f12
]

[Yb]
0 = [
    "Yb #n8", # Yb atom, s2f14
]
2 = [
    "Yb #c+2 #n7", # Yb2+, f14
]
3 = [
    "Yb #c+3 #n6 #u1", # Yb3+, f13
]

[Lu]
0 = [
    "Lu #n #u", # Lu atom, s2d1
]
3 = [
    "Lu #c+3", # Lu3+, d0
]

[Hf]
0 = [
    "Hf #n #u2", # Hf atom, s2d2
]
4 = [
    "Hf #c+4", # Hf4+, d0
]

[Ta]
0 = [
    "Ta #n #u3", # Ta atom, s2d3
]

[W]
0 = [
    "W #n #u4", # W atom, s2d4
]

[Re]
0 = [
    "Re #n #u5", # Re atom, s2d5
]

[Os]
0 = [
    "Os #n2 #u4", # Os atom, s2d6
]

[Ir]
0 = [
    "Ir #n3 #u3", # Ir atom, s2d7
]

[Pt]
0 = [
    "Pt #n4 #u2", # Pt atom, s1d9
]
2 = [
    "Pt #c+2 #n4", # Pt2+, d8 low-spin
]

[Au]
0 = [
    "Au #n5 #u", # Au atom, s1d10
]
1 = [
    "Au #c+ #n5", # Au+, d10
]
3 = [
    "Au #c+3 #n4",     # Au3+, d8 low-spin
    "Au #c+3 #n3 #u2", # Au3+, d8 high-spin
]

[Hg]
0 = [
    "Hg #n6", # Hg atom, s2d10
]
1 = [
    "Hg #c+ #n5 #v", # [Hg2]2+
]
2 = [
    "Hg #c+2 #n5", # Hg2+, d10
]

[Tl]
0 = [
    "Tl #n #u", # Tl atom, s2p1
]
1 = [
    "Tl #c+ #n", # Tl+
]
3 = [
    "Tl #c+3", # Tl3+
]

[Pb]
0 = [
    "Pb #n #u2", # Pb atom, s2p2
]
2 = [
    "Pb #c+2 #n", # Pb2+
]
4 = [
    "Pb #c+4", # Pb4+
]

[Bi]
0 = [
    "Bi #n #u3", # Bi atom, s2p3
]
3 = [
    "Bi #c+3 #n", # Bi3+
]

[Po]
0 = [
    "Po #n2 #u2", # Po atom, s2p4
]
-2 = [
    "Po #c-2 #n4", # Po2-
]

[At]
0 = [
    "At #n3 #v", # At2
    "At #n3 #u", # At atom, s2p5
]

[Rn]
0 = [
    "Rn #n3 #m2", # RnF2
    "Rn #n2 #m4", # RnF4
    "Rn #n #m6",  # RnF6, RnO3
    "Rn #n4",     # Rn atom, s2p6
]

[Fr]
0 = [
    "Fr #u", # Fr atom, s1
]
1 = [
    "Fr #c+", # Fr+
]

[Ra]
0 = [
    "Ra #n", # Ra atom, s2
]
2 = [
    "Ra #c+2", # Ra2+
]

[Ac]
0 = [
    "Ac #n #u", # Ac atom, s2d1
]
3 = [
    "Ac #c+3", # Ac3+, d0
]

[Th]
0 = [
    "Th #n #u2", # Th atom, s2d2
]
3 = [
    "Th #c+3 #u", # Th3+, d1 (DOI: 10.1007/1-4020-3598-5_20)
]
4 = [
    "Th #c+4", # Th4+, f0
]

[Pa]
0 = [
    "Pa #n #u3", # Pa atom, s2d1f2
]
4 = [
    "Pa #c+4 #u", # Pa4+, f1 (DOI: 10.1007/1-4020-3598-5_20)
]
5 = [
    "Pa #c+5", # Pa5+, f0
]

[U]
0 = [
    "U #n #u4", # U atom, s2d2f3
]
3 = [
    "U #c+3 #u3", # U3+, f3 (DOI: 10.1007/1-4020-3598-5_20)
]
4 = [
    "U #c+4 #u2", # U4+, f2 (DOI: 10.1007/1-4020-3598-5_20)
]
5 = [
    "U #c+5 #u", # U5+, f1 (DOI: 10.1007/1-4020-3598-5_20)
]
6 = [
    "U #c+6", # U6+, f0
]

[Np]
0 = [
    "Np #n #u5", # Np atom, s2d1f3
]
3 = [
    "Np #c+3 #u4", # Np3+, f4 (DOI: 10.1007/1-4020-3598-5_20)
]
4 = [
    "Np #c+4 #u3", # Np4+, f3 (DOI: 10.1007/1-4020-3598-5_20)
]
5 = [
    "Np #c+5 #u2", # Np5+, f2 (DOI: 10.1007/1-4020-3598-5_20)
]
6 = [
    "Np #c+6 #u", # Np6+, f1 (DOI: 10.1007/1-4020-3598-5_20)
]

[Pu]
0 = [
    "Pu #n #u6", # Pu atom, s2f6
]
3 = [
    "Pu #c+3 #u5", # Pu3+, f5 (DOI: 10.1007/1-4020-3598-5_20)
]
4 = [
    "Pu #c+4 #u4", # Pu4+, f4 (DOI: 10.1007/1-4020-3598-5_20)
]
5 = [
    "Pu #c+5 #u3", # Np5+, f3 (DOI: 10.1007/1-4020-3598-5_20)
]
6 = [
    "Pu #c+6 #u2", # Pu6+, f2 (DOI: 10.1007/1-4020-3598-5_20)
]
7 = [
    "Pu #c+7 #u", # Pu7+, f1 (DOI: 10.1007/1-4020-3598-5_20)
]

[Am]
0 = [
    "Am #n #u7", # Am atom, s2d1f6
]
2 = [
    "Am #c+2 #u7", # Am2+, f7 (DOI: 10.1007/1-4020-3598-5_20)
]
3 = [
    "Am #c+3 #u6", # Am3+, f6 (DOI: 10.1007/1-4020-3598-5_20)
]
4 = [
    "Am #c+4 #u5", # Am4+, f5 (DOI: 10.1007/1-4020-3598-5_20)
]

[Cm]
0 = [
    "Cm #n #u8", # Cm atom, s2d1f7
]
3 = [
    "Cm #c+3 #u7", # Cm3+, f7 (DOI: 10.1007/1-4020-3598-5_20)
]
4 = [
    "Cm #c+4 #u6", # Cm4+, f6 (DOI: 10.1007/1-4020-3598-5_20)
]

[Bk]
0 = [
    "Bk #n3 #u5", # Bk atom, s2f9
]
3 = [
    "Bk #c+3 #n1 #u6", # Bk3+, f8 (DOI: 10.1007/1-4020-3598-5_20)
]
4 = [
    "Bk #c+4 #u7", # Bk4+, f7 (DOI: 10.1007/1-4020-3598-5_20)
]

[Cf]
0 = [
    "Cf #n4 #u4", # Cf atom, s2f10
]
2 = [
    "Cf #c+2 #n3 #u4", # Cf2+, f10
]
3 = [
    "Cf #c+3 #n2 #u5", # Cf3+, f9 (DOI: 10.1007/1-4020-3598-5_20)
]
4 = [
    "Cf #c+4 #n1 #u6", # Cf4+, f8 (DOI: 10.1007/1-4020-3598-5_20)
]

[Es]
0 = [
    "Es #n5 #u3", # Es atom, s2f11
]
2 = [
    "Es #c+2 #n4 #u3", # Es2+, f11 (DOI: 10.1007/1-4020-3598-5_20)
]
3 = [
    "Es #c+3 #n3 #u4", # Es3+, f10 (DOI: 10.1007/1-4020-3598-5_20)
]

[Fm]
0 = [
    "Fm #n6 #u2", # Fm atom, s2f12
]
2 = [
    "Fm #c+2 #n5 #u2", # Fm2+, f12 (DOI: 10.1007/1-4020-3598-5_20)
]
3 = [
    "Fm #c+3 #n4 #u3", # Fm3+, f11 (DOI: 10.1007/1-4020-3598-5_20)
]

[Md]
0 = [
    "Md #n7 #u", # Md atom, s2f13
]
2 = [
    "Md #c+2 #n6 #u", # Md2+, f13 (DOI: 10.1007/1-4020-3598-5_20)
]
3 = [
    "Md #c+3 #n5 #u2", # Md3+, f12 (DOI: 10.1007/1-4020-3598-5_20)
]

[No]
0 = [
    "No #n8", # No atom, s2f14
]
2 = [
    "No #c+2 #n7", # No2+, f14 (DOI: 10.1007/1-4020-3598-5_20)
]

[Lr]
0 = [
    "Lr #n #u", # Lr atom, s2d1
]
3 = [
    "Lr #c+3", # Lr3+, d0
]

[Rf]
0 = [
    "Rf #n #u2", # Rf atom, s2d2
]

[Db]
0 = [
    "Db #n #u3", # Db atom, s2d3
]

[Sg]
0 = [
    "Sg #n #u4", # Sg atom, s2d4
]

[Bh]
0 = [
    "Bh #n #u5", # Bh atom, s2d5
]

[Hs]
0 = [
    "Hs #n2 #u4", # Hs atom, s2d6
]
