#!/usr/bin/env python3
"""Generate Rust source code for reference character tables.

Reads .lis files from materials/character_tables/table_data/ and produces
a Rust module with one function per group returning a ReferenceTable.

Source data: http://gernot-katzers-spice-pages.com/character_tables/

Usage:
    python3 scripts/generate_reference_tables.py > tests/reference_tables_data.rs
"""

import math
import os
import sys
from pathlib import Path

# Known irrational characters. Generated file uses std::f64::consts names so
# the Rust constant carries full precision instead of the truncated decimal
# from the source tables.
NAMED_CONSTANTS = [
    ("SQRT_2", math.sqrt(2.0)),
]
CONSTANT_TOL = 1e-3

# Groups to include. File name mapping: Cs→C1h.lis, Ci→S2.lis.
GROUPS = [
    "C1", "C2", "C3", "C4", "C5", "C6",
    "Ci", "Cs",
    "C2v", "C3v", "C4v", "C5v", "C6v",
    "C2h", "C3h", "C4h", "C5h", "C6h",
    "D2", "D3", "D4", "D5", "D6",
    "D2h", "D3h", "D4h", "D5h", "D6h",
    "D2d", "D3d", "D4d", "D5d", "D6d",
    "S4", "S6", "S8", "S10",
    "T", "Td", "Th",
    "O", "Oh",
    "I", "Ih",
]

FILE_NAME_MAP = {
    "Cs": "C1h",
    "Ci": "S2",
}

SCRIPT_DIR = Path(__file__).resolve().parent
WORKSPACE_ROOT = SCRIPT_DIR.parent.parent
TABLE_DIR = WORKSPACE_ROOT / "materials" / "character_tables" / "table_data"


def parse_lis(path: Path) -> dict:
    """Parse a .lis file into group_name, irrep_names, class_sizes, characters."""
    lines = path.read_text().splitlines()

    # Find first non-empty line (header)
    header_line = next(l for l in lines if l.strip())
    header_before_angles = header_line.split("<R>")[0]
    tokens = header_before_angles.split()

    group_name = tokens[0]

    # Parse class sizes
    class_sizes = []
    i = 1
    while i < len(tokens):
        try:
            n = int(tokens[i])
            class_sizes.append(n)
            i += 2  # skip the class label
        except ValueError:
            class_sizes.append(1)
            i += 1

    num_classes = len(class_sizes)

    # Parse irrep rows
    header_idx = next(i for i, l in enumerate(lines) if l.strip())
    irrep_names = []
    characters = []

    for line in lines[header_idx + 1:]:
        trimmed = line.strip()
        if not trimmed:
            break

        char_part = trimmed.split("<R>")[0] if "<R>" in trimmed else trimmed
        tokens = char_part.split()
        if not tokens:
            break

        name = tokens[0]
        # Skip '*' marker if present
        start = 2 if len(tokens) > 1 and tokens[1] == "*" else 1

        chars = []
        for t in tokens[start:]:
            try:
                chars.append(float(t))
            except ValueError:
                pass

        if len(chars) != num_classes:
            continue

        irrep_names.append(name)
        characters.append(chars)

    order = sum(class_sizes)
    return {
        "group_name": group_name,
        "irrep_names": irrep_names,
        "class_sizes": class_sizes,
        "characters": characters,
        "order": order,
    }


def format_f64(v: float) -> str:
    """Format a float as a Rust f64 literal."""
    if v == int(v) and abs(v) < 1e12:
        return f"{int(v)}.0"
    for name, value in NAMED_CONSTANTS:
        if abs(v - value) < CONSTANT_TOL:
            return name
        if abs(v + value) < CONSTANT_TOL:
            return f"-{name}"
    return f"{v}"


def format_table(group: str, data: dict) -> str:
    """Generate a Rust function returning a ReferenceTable for this group."""
    fn_name = group.lower().replace("*", "star")
    lines = []
    lines.append(f'    "{group}" => Some(ReferenceTable {{')
    lines.append(f'        group_name: "{data["group_name"]}".into(),')

    # irrep_names
    def escape_rust_str(s: str) -> str:
        return s.replace("\\", "\\\\").replace('"', '\\"')
    names = ", ".join(f'"{escape_rust_str(n)}".into()' for n in data["irrep_names"])
    lines.append(f"        irrep_names: vec![{names}],")

    # class_sizes
    sizes = ", ".join(str(s) for s in data["class_sizes"])
    lines.append(f"        class_sizes: vec![{sizes}],")

    # characters
    lines.append("        characters: vec![")
    for row in data["characters"]:
        vals = ", ".join(format_f64(v) for v in row)
        lines.append(f"            vec![{vals}],")
    lines.append("        ],")

    lines.append(f'        order: {data["order"]},')
    lines.append("    }),")
    return "\n".join(lines)


def main():
    if not TABLE_DIR.exists():
        print(f"Error: {TABLE_DIR} not found", file=sys.stderr)
        sys.exit(1)

    tables = {}
    for group in GROUPS:
        file_name = FILE_NAME_MAP.get(group, group)
        path = TABLE_DIR / f"{file_name}.lis"
        if not path.exists():
            print(f"Warning: {path} not found, skipping {group}", file=sys.stderr)
            continue
        tables[group] = parse_lis(path)

    # Generate Rust source
    print("// Auto-generated by scripts/generate_reference_tables.py")
    print("// Source: http://gernot-katzers-spice-pages.com/character_tables/")
    print("//")
    print("// Do not edit by hand.")
    print()
    print("use std::f64::consts::SQRT_2;")
    print()
    print("#[allow(dead_code)]")
    print("pub struct ReferenceTable {")
    print("    pub group_name: String,")
    print("    pub irrep_names: Vec<String>,")
    print("    pub class_sizes: Vec<i32>,")
    print("    pub characters: Vec<Vec<f64>>,")
    print("    pub order: usize,")
    print("}")
    print()
    print("#[allow(dead_code)]")
    print("pub fn reference_table(group: &str) -> Option<ReferenceTable> {")
    print("    match group {")
    for group in GROUPS:
        if group in tables:
            print(format_table(group, tables[group]))
    print('        _ => None,')
    print("    }")
    print("}")

    print(f"\nGenerated {len(tables)} tables", file=sys.stderr)


if __name__ == "__main__":
    main()
