//! Header parser for MOL files.

use bstr::ByteSlice;
use nom::character::complete::{line_ending, not_line_ending};
use nom::combinator::map;
use nom::error::Error as NomError;
use nom::sequence::terminated;
use nom::Parser;

/// Parse a single line from the MOL header
fn header_input<'inp>() -> impl Parser<&'inp [u8], Output = String, Error = NomError<&'inp [u8]>> {
    map(not_line_ending, |s: &[u8]| s.to_str_lossy().into_owned())
}

/// Parse the 3-line MOL file header block (name, program info, comment)
///
/// Returns a Vec of 3 strings: [name, program_info, comment]
pub(super) fn header_block<'inp>(
) -> impl Parser<&'inp [u8], Output = Vec<String>, Error = NomError<&'inp [u8]>> {
    map(
        (
            terminated(header_input(), line_ending),
            terminated(header_input(), line_ending),
            terminated(header_input(), line_ending),
        ),
        |(name, program_info, comment)| vec![name, program_info, comment],
    )
}

#[cfg(test)]
mod tests {
    use nom::combinator::all_consuming;
    use rstest::*;

    use super::*;

    #[rstest]
    #[case::valid(
        b"Caffeine\nRDKit          3D\nGenerated by RDKit\n",
        vec!["Caffeine".to_string(), "RDKit          3D".to_string(), "Generated by RDKit".to_string()]
    )]
    #[case::empty(
        b"\n\n\n",
        vec!["".to_string(), "".to_string(), "".to_string()]
    )]
    #[case::whitespace(
        b"  Molecule Name  \n  Program Info  \n  Comment Line  \n",
        vec!["  Molecule Name  ".to_string(), "  Program Info  ".to_string(), "  Comment Line  ".to_string()]
    )]
    fn test_header_block(#[case] input: &[u8], #[case] expected: Vec<String>) {
        let result = all_consuming(header_block()).parse(input);
        assert!(result.is_ok(), "should have succeeded: {:?}", result.err());
        let (remaining, header) = result.unwrap();
        assert!(remaining.is_empty(), "has remaining data");
        assert_eq!(header, expected);
    }
}
