//! Header parser for MOL files.

use bstr::ByteSlice;
use nom::Err;

use super::utils::LinesWithOffsetExt;
use crate::io::ctfile::error::ParseError;

/// Parse the 3-line MOL file header block (name, program info, comment)
///
/// Returns (Vec of 3 strings, updated line offset)
pub(super) fn header_block<'inp>(
    line_offset: u32,
) -> impl FnMut(&'inp [u8]) -> Result<(&'inp [u8], (Vec<String>, u32)), Err<ParseError>> {
    move |input: &'inp [u8]| {
        let mut lines_iter = input.lines_with_offset();
        let mut headers = Vec::with_capacity(3);
        let mut byte_offset = 0;

        for i in 0..3 {
            let (line, byte_len) = lines_iter.next().ok_or_else(|| {
                Err::Error(ParseError::UnexpectedEof {
                    line: line_offset + i,
                    block: "header",
                })
            })?;
            headers.push(line.to_str_lossy().into_owned());
            byte_offset += byte_len;
        }

        let remaining = &input[byte_offset..];
        Ok((remaining, (headers, line_offset + 3)))
    }
}

#[cfg(test)]
mod tests {
    use nom::Parser;
    use rstest::*;

    use super::*;

    #[rstest]
    #[case::valid(
        b"Caffeine\nRDKit          3D\nGenerated by RDKit\n",
        vec!["Caffeine".to_string(), "RDKit          3D".to_string(), "Generated by RDKit".to_string()]
    )]
    #[case::empty(
        b"\n\n\n",
        vec!["".to_string(), "".to_string(), "".to_string()]
    )]
    #[case::whitespace(
        b"  Molecule Name  \n  Program Info  \n  Comment Line  \n",
        vec!["  Molecule Name  ".to_string(), "  Program Info  ".to_string(), "  Comment Line  ".to_string()]
    )]
    #[case::crlf(
        b"Name\r\nProgram\r\nComment\r\n",
        vec!["Name".to_string(), "Program".to_string(), "Comment".to_string()]
    )]
    fn test_header_block(#[case] input: &[u8], #[case] expected: Vec<String>) {
        let result = header_block(0).parse(input);
        assert!(result.is_ok(), "should have succeeded: {:?}", result.err());
        let (remaining, (headers, line_offset)) = result.unwrap();
        assert!(remaining.is_empty(), "has remaining data");
        assert_eq!(headers, expected);
        assert_eq!(line_offset, 3);
    }

    #[rstest]
    #[case::two_lines(b"Line1\nLine2\n", Err::Error(ParseError::UnexpectedEof { line: 2, block: "header" }))]
    fn test_header_block_invalid(#[case] input: &[u8], #[case] expected_error: Err<ParseError>) {
        let result = header_block(0).parse(input);
        assert!(result.is_err());
        assert_eq!(result.unwrap_err(), expected_error);
    }
}
