[package]
name = "umol-graph-core"
version = "0.1.0"
authors = ["Dmitrij Rappoport <dmitrij@rappoport.org>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rappoport/umol"
description = "Graph data structures and algorithms for umol."

[lib]
bench = false

[dependencies]
nauty-Traces-sys = { version = "0.11", features = ["bundled", "tls"] }

[dev-dependencies]
criterion = "0.8.1"
pretty_assertions = "1.4.1"
rstest = "0.26.1"

[[bench]]
name = "algorithms"
harness = false

[lints.clippy]
absolute_paths = "warn"
mod_module_files = "warn"
