//! Error types.
//!
//! [`EdnError`] is the public dispatch enum. It wraps three narrower
//! sub-concern types that correspond to the three failure domains in the
//! crate:
//!
//! - [`ParseError`] — syntactic failures while reading EDN text.
//! - [`DeError`] — schema/shape failures while turning an [`Edn`] tree
//!   into a Rust value (`FromEdn` and the serde `Deserializer`).
//! - [`SerError`] — failures while turning a Rust value into EDN (the
//!   serde `Serializer`; native `ToEdn` is infallible).
//!
//! The sub-enums are re-exported so callers who want to match on a
//! specific category can `match err { EdnError::Parse(e) => … }`. The
//! `#[from]` impls generated by `thiserror` let internal code construct
//! the narrow type and rely on `?` to lift it into `EdnError`.
//!
//! [`Edn`]: crate::edn::Edn

#[cfg(feature = "serde")]
use std::fmt;

use thiserror::Error;
use winnow::error::{ErrMode, ParserError};
use winnow::stream::Location;
use winnow::LocatingSlice;

#[cfg(feature = "serde")]
use serde::de::Error as SerdeDeError;
#[cfg(feature = "serde")]
use serde::ser::Error as SerdeSerError;

/// EDN error. Dispatches to one of [`ParseError`], [`DeError`], or
/// [`SerError`] depending on which phase failed.
#[derive(Clone, Debug, PartialEq, Eq, Error)]
pub enum EdnError {
    #[error(transparent)]
    Parse(#[from] ParseError),
    #[error(transparent)]
    De(#[from] DeError),
    #[error(transparent)]
    Ser(#[from] SerError),
}

/// Syntactic errors raised while reading EDN text.
#[derive(Clone, Debug, PartialEq, Eq, Error)]
pub enum ParseError {
    #[error("unexpected end of input at byte {offset}")]
    UnexpectedEof { offset: usize },
    #[error("unexpected token '{found}' at byte {offset}")]
    UnexpectedToken { offset: usize, found: char },
    #[error("invalid number at byte {offset}")]
    InvalidNumber { offset: usize },
    #[error("invalid escape sequence at byte {offset}")]
    InvalidEscape { offset: usize },
    #[error("invalid character literal at byte {offset}")]
    InvalidCharLiteral { offset: usize },
    #[error("invalid symbol at byte {offset}")]
    InvalidSymbol { offset: usize },
    #[error("duplicate map key at byte {offset}")]
    DuplicateKey { offset: usize },
    #[error("invalid tag '{tag}' at byte {offset}")]
    InvalidTag { offset: usize, tag: String },
    #[error("invalid #inst: {reason}")]
    InvalidInst { reason: String },
    #[error("invalid #uuid: {reason}")]
    InvalidUuid { reason: String },
    #[error("trailing content at byte {offset}")]
    TrailingContent { offset: usize },
    #[error("unsupported feature '{feature}' at byte {offset}")]
    UnsupportedFeature {
        offset: usize,
        feature: &'static str,
    },
    #[error("recursion limit exceeded at byte {offset}")]
    RecursionLimit { offset: usize },
    #[error("invalid UTF-8 at byte {offset}")]
    InvalidUtf8 { offset: usize },
}

/// Errors raised while turning an [`Edn`] tree into a Rust value.
///
/// Raised by [`FromEdn`] impls, the [`EdnMapHelper`] builder, and the
/// serde `Deserializer`. The serde path leaves `path` empty because
/// serde does not expose the current field/index location to the
/// `Deserializer`.
///
/// [`Edn`]: crate::edn::Edn
/// [`FromEdn`]: crate::traits::FromEdn
/// [`EdnMapHelper`]: crate::collections::EdnMapHelper
#[derive(Clone, Debug, PartialEq, Eq, Error)]
pub enum DeError {
    #[error("missing required field '{key}' at {}", fmt_path(path))]
    MissingField { key: String, path: Vec<String> },
    #[error("unknown field '{key}' at {}", fmt_path(path))]
    UnknownField { key: String, path: Vec<String> },
    #[error("type mismatch at {}: expected {expected}, got {got}", fmt_path(path))]
    TypeMismatch {
        expected: &'static str,
        got: &'static str,
        path: Vec<String>,
    },
    #[error("value '{value}' out of range for {target} at {}", fmt_path(path))]
    OutOfRange {
        value: String,
        target: &'static str,
        path: Vec<String>,
    },
    #[error("unsupported: {0}")]
    Unsupported(&'static str),
    #[error("{0}")]
    Custom(String),
}

/// Errors raised while turning a Rust value into EDN via the serde
/// `Serializer`. Native `ToEdn` is infallible, so this is only reached
/// through the `serde` feature.
#[derive(Clone, Debug, PartialEq, Eq, Error)]
pub enum SerError {
    #[error("EDN cannot represent {0}")]
    UnsupportedFloat(&'static str),
    #[error("unsupported: {0}")]
    Unsupported(&'static str),
    #[error("value '{value}' out of range for {target}")]
    OutOfRange {
        value: String,
        target: &'static str,
    },
    #[error("{0}")]
    Custom(String),
}

/// Format a `path` slice as a dotted EDN access path for error messages.
/// Empty path renders as `<root>`.
fn fmt_path(path: &[String]) -> String {
    if path.is_empty() {
        "<root>".to_string()
    } else {
        path.join("")
    }
}

impl<'a> ParserError<LocatingSlice<&'a str>> for ParseError {
    type Inner = Self;

    fn from_input(input: &LocatingSlice<&'a str>) -> Self {
        let offset = input.current_token_start();
        match input.as_ref().chars().next() {
            Some(c) => ParseError::UnexpectedToken { offset, found: c },
            None => ParseError::UnexpectedEof { offset },
        }
    }

    fn into_inner(self) -> Result<Self::Inner, Self> {
        Ok(self)
    }
}

/// Extract `ParseError` from `ErrMode<ParseError>`.
pub(crate) fn unwrap_err(e: ErrMode<ParseError>) -> ParseError {
    match e {
        ErrMode::Backtrack(e) | ErrMode::Cut(e) => e,
        // Incomplete means the parser needs more input — treat as EOF.
        // No precise offset is available from winnow's Incomplete variant;
        // report 0 (callers that know the input length can improve this).
        ErrMode::Incomplete(_) => ParseError::UnexpectedEof { offset: 0 },
    }
}

#[cfg(feature = "serde")]
impl SerdeDeError for EdnError {
    fn custom<T: fmt::Display>(msg: T) -> Self {
        EdnError::De(DeError::Custom(msg.to_string()))
    }
}

#[cfg(feature = "serde")]
impl SerdeSerError for EdnError {
    fn custom<T: fmt::Display>(msg: T) -> Self {
        EdnError::Ser(SerError::Custom(msg.to_string()))
    }
}
