[package]
name = "umol-edn-macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords = ["edn", "macros", "parser", "data-format"]
description = "Procedural macros for the umol EDN parser."

[lib]
proc-macro = true

[dependencies]
heck = "0.5"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2", features = ["full"] }
