//! Subgroups of the symmetric group Sₙ, fully enumerated (n ≤ 6).

use std::collections::HashSet;

use crate::permutation::Permutation;

/// A subgroup of Sₙ, stored as its full element set, sorted in Lehmer order.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PermutationGroup {
    degree: usize,
    elements: Vec<Permutation>,
}

impl PermutationGroup {
    /// The subgroup generated by `generators` — the closure of `{identity} ∪
    /// generators` under composition. Panics unless every generator has the
    /// requested degree.
    pub fn generate(degree: usize, generators: &[Permutation]) -> Self {
        assert!(
            generators
                .iter()
                .all(|generator| generator.degree() == degree),
            "generator degree must equal group degree"
        );
        let identity = Permutation::identity(degree);
        let mut seen: HashSet<Permutation> = HashSet::from([identity]);
        let mut frontier = vec![identity];
        while let Some(element) = frontier.pop() {
            for &generator in generators {
                let product = generator.compose(element);
                if seen.insert(product) {
                    frontier.push(product);
                }
            }
        }
        Self::from_set(degree, seen)
    }

    /// The full symmetric group Sₙ.
    pub fn symmetric(degree: usize) -> Self {
        let order: usize = (1..=degree).product();
        Self::from_set(degree, (0..order).map(|i| Permutation::unrank(degree, i)))
    }

    /// The alternating group Aₙ — the even permutations.
    pub fn alternating(degree: usize) -> Self {
        let order: usize = (1..=degree).product();
        Self::from_set(
            degree,
            (0..order)
                .map(|i| Permutation::unrank(degree, i))
                .filter(|p| p.sign() == 1),
        )
    }

    /// The cyclic group Cₙ generated by the n-cycle `(0 1 … n-1)`. Panics if
    /// `degree == 0`.
    pub fn cyclic(degree: usize) -> Self {
        assert!(degree > 0, "cyclic group degree must be positive");
        Self::generate(degree, &[Self::rotation(degree)])
    }

    /// The dihedral group Dₙ (order 2n) of the n-gon: an n-cycle plus a reflection.
    /// Panics if `degree == 0`.
    pub fn dihedral(degree: usize) -> Self {
        assert!(degree > 0, "dihedral group degree must be positive");
        Self::generate(degree, &[Self::rotation(degree), Self::reflection(degree)])
    }

    pub fn degree(&self) -> usize {
        self.degree
    }

    pub fn order(&self) -> usize {
        self.elements.len()
    }

    /// Whether `permutation` belongs to this group. A permutation of another
    /// degree is not a member.
    pub fn contains(&self, permutation: &Permutation) -> bool {
        permutation.degree() == self.degree && self.elements.binary_search(permutation).is_ok()
    }

    pub fn elements(&self) -> &[Permutation] {
        &self.elements
    }

    fn from_set(degree: usize, set: impl IntoIterator<Item = Permutation>) -> Self {
        let mut elements: Vec<Permutation> = set.into_iter().collect();
        elements.sort();
        Self { degree, elements }
    }

    fn rotation(degree: usize) -> Permutation {
        let image: Vec<usize> = (0..degree).map(|i| (i + 1) % degree).collect();
        Permutation::from_image(&image)
    }

    fn reflection(degree: usize) -> Permutation {
        let image: Vec<usize> = (0..degree).map(|i| (degree - i) % degree).collect();
        Permutation::from_image(&image)
    }
}

#[cfg(test)]
mod tests {
    use pretty_assertions::assert_eq;
    use rstest::*;

    use super::*;

    #[rstest]
    fn test_permutation_group_generate() {
        let transposition = Permutation::from_image(&[1, 0, 2]);
        let group = PermutationGroup::generate(3, &[transposition]);
        assert_eq!(group.order(), 2);
        assert!(group.contains(&Permutation::identity(3)));
        assert!(group.contains(&transposition));
    }

    #[rstest]
    #[case::smaller(Permutation::identity(2))]
    #[case::larger(Permutation::identity(4))]
    #[should_panic(expected = "generator degree must equal group degree")]
    fn test_permutation_group_generate_error(#[case] generator: Permutation) {
        PermutationGroup::generate(3, &[generator]);
    }

    #[rstest]
    #[case::s2(2, 2)]
    #[case::s3(3, 6)]
    #[case::s4(4, 24)]
    fn test_permutation_group_symmetric(#[case] degree: usize, #[case] order: usize) {
        assert_eq!(PermutationGroup::symmetric(degree).order(), order);
    }

    #[rstest]
    #[case::a3(3, 3)]
    #[case::a4(4, 12)]
    fn test_permutation_group_alternating(#[case] degree: usize, #[case] order: usize) {
        let group = PermutationGroup::alternating(degree);
        assert_eq!(group.order(), order);
        assert!(group.elements().iter().all(|p| p.sign() == 1));
    }

    #[rstest]
    #[case::c4(4, 4)]
    #[case::c6(6, 6)]
    fn test_permutation_group_cyclic(#[case] degree: usize, #[case] order: usize) {
        assert_eq!(PermutationGroup::cyclic(degree).order(), order);
    }

    #[rstest]
    #[should_panic(expected = "cyclic group degree must be positive")]
    fn test_permutation_group_cyclic_error() {
        PermutationGroup::cyclic(0);
    }

    #[rstest]
    #[case::d3(3, 6)]
    #[case::d4(4, 8)]
    #[case::d5(5, 10)]
    fn test_permutation_group_dihedral(#[case] degree: usize, #[case] order: usize) {
        assert_eq!(PermutationGroup::dihedral(degree).order(), order);
    }

    #[rstest]
    #[should_panic(expected = "dihedral group degree must be positive")]
    fn test_permutation_group_dihedral_error() {
        PermutationGroup::dihedral(0);
    }

    #[rstest]
    #[case::member(Permutation::from_image(&[1, 2, 0]), true)]
    #[case::non_member(Permutation::from_image(&[1, 0, 2]), false)]
    #[case::smaller_degree(Permutation::identity(2), false)]
    #[case::larger_degree(Permutation::identity(4), false)]
    fn test_permutation_group_contains(#[case] permutation: Permutation, #[case] expected: bool) {
        let group = PermutationGroup::alternating(3);
        assert_eq!(group.contains(&permutation), expected);
    }
}
