//! Orientation-graded permutations and their groups: the permutation-inversion
//! element π·E^k of Sₙ×Z₂ (proper rotation × mirror parity).

use std::collections::HashSet;

use crate::group::PermutationGroup;
use crate::permutation::Permutation;

/// Orientation grade: proper rotation vs improper (mirror) operation.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum Orientation {
    Proper,
    Improper,
}

impl Orientation {
    /// The Z₂ product: improper∘improper = proper.
    pub fn compose(self, other: Orientation) -> Orientation {
        if self == other {
            Orientation::Proper
        } else {
            Orientation::Improper
        }
    }

    pub fn flip(self) -> Orientation {
        match self {
            Orientation::Proper => Orientation::Improper,
            Orientation::Improper => Orientation::Proper,
        }
    }

    pub fn is_proper(self) -> bool {
        self == Orientation::Proper
    }
}

/// A permutation carrying a proper/improper grade.
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct OrientedPermutation {
    permutation: Permutation,
    orientation: Orientation,
}

impl OrientedPermutation {
    pub fn new(permutation: Permutation, orientation: Orientation) -> Self {
        Self {
            permutation,
            orientation,
        }
    }

    pub fn proper(permutation: Permutation) -> Self {
        Self::new(permutation, Orientation::Proper)
    }

    pub fn improper(permutation: Permutation) -> Self {
        Self::new(permutation, Orientation::Improper)
    }

    pub fn identity(degree: usize) -> Self {
        Self::proper(Permutation::identity(degree))
    }

    pub fn permutation(self) -> Permutation {
        self.permutation
    }

    pub fn orientation(self) -> Orientation {
        self.orientation
    }

    pub fn is_proper(self) -> bool {
        self.orientation.is_proper()
    }

    pub fn degree(self) -> usize {
        self.permutation.degree()
    }

    /// σ(i). The orientation is a parity bit, not a point map.
    pub fn apply(self, i: usize) -> usize {
        self.permutation.apply(i)
    }

    /// `(σ, a) ∘ (τ, b) = (σ∘τ, a·b)`.
    pub fn compose(self, other: Self) -> Self {
        Self::new(
            self.permutation.compose(other.permutation),
            self.orientation.compose(other.orientation),
        )
    }

    pub fn inverse(self) -> Self {
        Self::new(self.permutation.inverse(), self.orientation)
    }
}

/// A subgroup of Sₙ×Z₂, stored as the proper subgroup plus (if present) one
/// improper coset representative: the improper elements are
/// `{ improper_rep ∘ p : p ∈ proper }`. The representative is canonical (the
/// improper element of minimum Lehmer rank), so equal groups compare equal.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct OrientedPermutationGroup {
    proper: PermutationGroup,
    improper_rep: Option<OrientedPermutation>,
}

impl OrientedPermutationGroup {
    /// The subgroup generated by `generators`, closed under composition.
    pub fn generate(degree: usize, generators: &[OrientedPermutation]) -> Self {
        let identity = OrientedPermutation::identity(degree);
        let mut seen: HashSet<OrientedPermutation> = HashSet::from([identity]);
        let mut frontier = vec![identity];
        while let Some(element) = frontier.pop() {
            for &generator in generators {
                let product = generator.compose(element);
                if seen.insert(product) {
                    frontier.push(product);
                }
            }
        }
        let mut proper = Vec::new();
        let mut improper_rep: Option<OrientedPermutation> = None;
        for op in seen {
            if op.is_proper() {
                proper.push(op.permutation());
            } else if improper_rep
                .is_none_or(|rep| op.permutation().rank() < rep.permutation().rank())
            {
                improper_rep = Some(op);
            }
        }
        Self {
            proper: PermutationGroup::generate(degree, &proper),
            improper_rep,
        }
    }

    pub fn degree(&self) -> usize {
        self.proper.degree()
    }

    pub fn order(&self) -> usize {
        self.proper.order() * (1 + usize::from(self.improper_rep.is_some()))
    }

    pub fn contains(&self, op: OrientedPermutation) -> bool {
        if op.is_proper() {
            self.proper.contains(&op.permutation())
        } else {
            match self.improper_rep {
                Some(rep) => self
                    .proper
                    .contains(&rep.inverse().compose(op).permutation()),
                None => false,
            }
        }
    }

    /// The proper subgroup as proper-graded elements, then the improper coset.
    pub fn elements(&self) -> Vec<OrientedPermutation> {
        let mut result: Vec<OrientedPermutation> = self
            .proper
            .elements()
            .iter()
            .map(|&permutation| OrientedPermutation::proper(permutation))
            .collect();
        if let Some(rep) = self.improper_rep {
            for &p in self.proper.elements() {
                result.push(rep.compose(OrientedPermutation::proper(p)));
            }
        }
        result
    }

    pub fn proper(&self) -> &PermutationGroup {
        &self.proper
    }

    pub fn improper_rep(&self) -> Option<OrientedPermutation> {
        self.improper_rep
    }

    /// Orbit of `point` under the proper subgroup (homotopic positions).
    pub fn proper_orbit_of(&self, point: usize) -> Vec<usize> {
        sorted_orbit(self.proper.elements().iter().map(|p| p.apply(point)))
    }

    /// Orbit of `point` under the full group (star: homotopic ∪ enantiotopic).
    pub fn star_orbit_of(&self, point: usize) -> Vec<usize> {
        sorted_orbit(self.elements().iter().map(|op| op.apply(point)))
    }
}

fn sorted_orbit(images: impl Iterator<Item = usize>) -> Vec<usize> {
    let mut orbit: Vec<usize> = images.collect();
    orbit.sort_unstable();
    orbit.dedup();
    orbit
}

#[cfg(test)]
mod tests {
    use pretty_assertions::assert_eq;
    use rstest::*;

    use super::*;

    #[rstest]
    #[case::proper_proper(Orientation::Proper, Orientation::Proper, Orientation::Proper)]
    #[case::proper_improper(Orientation::Proper, Orientation::Improper, Orientation::Improper)]
    #[case::improper_improper(Orientation::Improper, Orientation::Improper, Orientation::Proper)]
    fn test_orientation_compose(
        #[case] a: Orientation,
        #[case] b: Orientation,
        #[case] expected: Orientation,
    ) {
        assert_eq!(a.compose(b), expected);
    }

    #[rstest]
    #[case::proper(Orientation::Proper, Orientation::Improper)]
    #[case::improper(Orientation::Improper, Orientation::Proper)]
    fn test_orientation_flip(#[case] o: Orientation, #[case] expected: Orientation) {
        assert_eq!(o.flip(), expected);
    }

    #[rstest]
    fn test_oriented_permutation_compose() {
        let a = OrientedPermutation::proper(Permutation::from_image(3, &[1, 2, 0]));
        let b = OrientedPermutation::improper(Permutation::from_image(3, &[1, 0, 2]));
        assert_eq!(
            a.compose(b),
            OrientedPermutation::improper(Permutation::from_image(3, &[2, 1, 0]))
        );
    }

    #[rstest]
    fn test_oriented_permutation_inverse() {
        let a = OrientedPermutation::improper(Permutation::from_image(3, &[1, 2, 0]));
        assert_eq!(
            a.inverse(),
            OrientedPermutation::improper(Permutation::from_image(3, &[2, 0, 1]))
        );
    }

    #[rstest]
    #[case::proper_identity(OrientedPermutation::identity(4), 0)]
    #[case::improper_transposition(
        OrientedPermutation::improper(Permutation::from_image(4, &[1, 0, 2, 3])),
        1
    )]
    fn test_oriented_permutation_apply(#[case] op: OrientedPermutation, #[case] image_of_0: usize) {
        assert_eq!(op.apply(0), image_of_0);
    }

    #[rstest]
    fn test_oriented_permutation_group_generate() {
        let group = OrientedPermutationGroup::generate(
            4,
            &[
                OrientedPermutation::proper(Permutation::from_image(4, &[1, 0, 3, 2])),
                OrientedPermutation::improper(Permutation::from_image(4, &[2, 3, 0, 1])),
            ],
        );
        assert_eq!(group.order(), 4);
        assert_eq!(group.proper().order(), 2);
        assert_eq!(
            group.improper_rep(),
            Some(OrientedPermutation::improper(Permutation::from_image(
                4,
                &[2, 3, 0, 1]
            )))
        );
    }

    #[rstest]
    #[case::proper_member(
        OrientedPermutation::proper(Permutation::from_image(4, &[1, 0, 3, 2])),
        true
    )]
    #[case::improper_rep(
        OrientedPermutation::improper(Permutation::from_image(4, &[2, 3, 0, 1])),
        true
    )]
    #[case::improper_coset_member(
        OrientedPermutation::improper(Permutation::from_image(4, &[3, 2, 1, 0])),
        true
    )]
    #[case::proper_non_member(
        OrientedPermutation::proper(Permutation::from_image(4, &[2, 3, 0, 1])),
        false
    )]
    #[case::improper_non_member(
        OrientedPermutation::improper(Permutation::from_image(4, &[1, 0, 2, 3])),
        false
    )]
    fn test_oriented_permutation_group_contains(
        #[case] op: OrientedPermutation,
        #[case] expected: bool,
    ) {
        let group = OrientedPermutationGroup::generate(
            4,
            &[
                OrientedPermutation::proper(Permutation::from_image(4, &[1, 0, 3, 2])),
                OrientedPermutation::improper(Permutation::from_image(4, &[2, 3, 0, 1])),
            ],
        );
        assert_eq!(group.contains(op), expected);
    }

    #[rstest]
    fn test_oriented_permutation_group_elements() {
        let group = OrientedPermutationGroup::generate(
            2,
            &[OrientedPermutation::improper(Permutation::from_image(
                2,
                &[1, 0],
            ))],
        );
        assert_eq!(
            group.elements(),
            vec![
                OrientedPermutation::proper(Permutation::identity(2)),
                OrientedPermutation::improper(Permutation::from_image(2, &[1, 0])),
            ]
        );
    }

    #[rstest]
    fn test_oriented_permutation_group_proper_orbit_of() {
        let group = OrientedPermutationGroup::generate(
            4,
            &[
                OrientedPermutation::proper(Permutation::from_image(4, &[1, 0, 3, 2])),
                OrientedPermutation::improper(Permutation::from_image(4, &[2, 3, 0, 1])),
            ],
        );
        assert_eq!(group.proper_orbit_of(0), vec![0, 1]);
    }

    #[rstest]
    fn test_oriented_permutation_group_star_orbit_of() {
        let group = OrientedPermutationGroup::generate(
            4,
            &[
                OrientedPermutation::proper(Permutation::from_image(4, &[1, 0, 3, 2])),
                OrientedPermutation::improper(Permutation::from_image(4, &[2, 3, 0, 1])),
            ],
        );
        assert_eq!(group.star_orbit_of(0), vec![0, 1, 2, 3]);
    }
}
