//! Header parser for MOL files.

use nom::character::complete::{line_ending, not_line_ending};
use nom::combinator::map;
use nom::error;
use nom::sequence::terminated;
use nom::Parser;

use crate::molecule::Header;

/// Parse a single line from the MOL header
pub(crate) fn header_input<'a>(
) -> impl Parser<&'a [u8], Output = String, Error = error::Error<&'a [u8]>> {
    map(terminated(not_line_ending, line_ending), |s: &[u8]| {
        String::from_utf8_lossy(s).to_string()
    })
}

/// Parse the 3-line MOL file header (title, program info, comment)
pub fn header<'a>() -> impl Parser<&'a [u8], Output = Header, Error = error::Error<&'a [u8]>> {
    map(
        (header_input(), header_input(), header_input()),
        |(title, program_info, comment)| Header::new(title, program_info, comment),
    )
}

#[cfg(test)]
mod tests {
    use nom::combinator::all_consuming;

    use super::*;
    use rstest::*;

    #[rstest]
    #[case(
        b"Caffeine\nRDKit          3D\nGenerated by RDKit\n",
        "valid",
        Header::new("Caffeine".to_string(), "RDKit          3D".to_string(), "Generated by RDKit".to_string())
    )]
    #[case(b"\n\n\n", "empty", Header::new("".to_string(), "".to_string(), "".to_string()))]
    #[case(
        b"  Molecule Name  \n  Program Info  \n  Comment Line  \n",
        "whitespace",
        Header::new("  Molecule Name  ".to_string(), "  Program Info  ".to_string(), "  Comment Line  ".to_string())
    )]
    fn test_header(#[case] input: &[u8], #[case] desc: &str, #[case] expected: Header) {
        let result = all_consuming(header()).parse(input);
        assert!(result.is_ok(), "{} should have succeeded", desc);
        let (remaining, header) = result.unwrap();
        assert!(remaining.is_empty(), "{} has remaining data", desc);
        assert_eq!(header.title, expected.title);
        assert_eq!(header.program_info, expected.program_info);
        assert_eq!(header.comment, expected.comment);
    }
}
