atom_types = [
    # Hydrogen
    "[H+0v1]",
    "[H+1v0]",
    "[H-1/1v0]",

    # Lithium
    "[Li+1v0]",
    "[Li+0v1]",

    # Boron
    "[B+0v3]",
    "[B+0^1v2]",
    "[B+0/1v1]",
    "[B-1v4]",

    # Carbon
    "[C+0v4]",
    "[C+0^1v3]",
    "[C+0/1^2v2]",
    "[C+1v3]",
    "[C-1/1v3]",

    # Nitrogen
    "[N+0/1v3]",
    "[N+0/1^1v2]",
    "[N+0/2^2*3v1]",
    "[N+1v4]",
    "[N+1/1v2]",
    "[N-1/2v2]",
    "[N-3/4v0]",

    # Oxygen
    "[O+0/2v2]",
    "[O+0/2^1v1]",
    "[O+1/1v3]",
    "[O+1/2v1]",
    "[O-1/3v1]",
    "[O-2/4v0]",

    # Fluorine
    "[F+0/3v1]",
    "[F+0/3^1v0]",
    "[F-1/4v0]",

    # Sodium
    "[Na+1v0]",

    # Magnesium
    "[Mg+2v0]",
    "[Mg+0v2]",

    # Aluminum
    "[Al+0v3]",
    "[Al+3v0]",

    # Silicon
    "[Si+0v4]",
    "[Si+0v2]",
    "[Si+0^1v3]",

    # Phosphorus
    "[P+0/1v3]",
    "[P+0v5]",
    "[P+1v4]",
    "[P-1/2v3]",

    # Sulfur
    "[S+0/2v2]",
    "[S+0/2^1v1]",
    "[S+0/1v4]",
    "[S+0v6]",
    "[S+1/1v3]",
    "[S-1/3v1]",
    "[S-2/4v0]",

    # Chlorine
    "[Cl+0/3v1]",
    "[Cl+0/3^1v0]",
    "[Cl+0v3]",
    "[Cl+0v5]",
    "[Cl+1/2v2]",
    "[Cl-1/4v0]",

    # Potassium
    "[K+1v0]",

    # Calcium
    "[Ca+2v0]",

    # Selenium
    "[Se+0/2v2]",
    "[Se+0/2^1v1]",
    "[Se+0v4]",
    "[Se+0v6]",
    "[Se-1/3v1]",
    "[Se-2/4v0]",

    # Bromine
    "[Br+0/3v1]",
    "[Br+0/3^1v0]",
    "[Br+0v3]",
    "[Br+0v5]",
    "[Br+1/2v2]",
    "[Br-1/4v0]",

    # Iodine
    "[I+0/3v1]",
    "[I+0/3^1v0]",
    "[I+0v3]",
    "[I+0v5]",
    "[I+1/2v2]",
    "[I-1/4v0]",
]
