[package]
name = "umol-ast-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
libfuzzer-sys = "0.4"
umol-ast = { path = ".." }
umol-edn = { path = "../../umol-edn" }
umol-graph-core = { path = "../../umol-graph-core" }

[[bin]]
name = "fuzz_entity_strings"
path = "fuzz_targets/fuzz_entity_strings.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_molecule"
path = "fuzz_targets/fuzz_molecule.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_constraints"
path = "fuzz_targets/fuzz_constraints.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_reaction"
path = "fuzz_targets/fuzz_reaction.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_reaction_span"
path = "fuzz_targets/fuzz_reaction_span.rs"
test = false
doc = false
bench = false
