[package]
name = "umol-models-geometric"
version = "0.1.0"
authors = ["Dmitrij Rappoport <dmitrij@rappoport.org>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rappoport/umol"
keywords = ["chemistry", "cheminformatics", "molecular parsing"]
edition = "2021"

[dependencies]
umol = { path = "../umol" }
umol-data = { path = "../umol-data" }
nom = { version = "8.0.0" }
num = "0.4.3"
num-traits = "0.2.19"
nalgebra = "0.34"

[dev-dependencies]
rstest = "0.26"
criterion = "0.7"