[package]
name = "umol-models-geometric"
version = "0.1.0"
authors = ["Dmitrij Rappoport <dmitrij@rappoport.org>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rappoport/umol"
keywords = ["chemistry", "cheminformatics", "molecular parsing"]
edition = "2021"

[dependencies]
nalgebra = "0.34.0"
nom = { version = "8.0.0" }
num = "0.4.3"
num-traits = "0.2.19"
umol = { path = "../umol" }
umol-data = { path = "../umol-data" }

[dev-dependencies]
rstest = "0.26.1"
criterion = "0.7.0"

[lib]
bench = false
