[H]
0 = [
    "{Hv1}", # H-X
    "{H^1}", # H atom
    # "{HH1}", # HH
]
1 = [
    "{H+}", # H+
]
-1 = [
    "{H-/1}", # H-
]

[He]
0 = [
    "{He/1}", # He atom
]

[Li]
0 = [
    "{Liv1}", # Li-X
    "{Li^1}", # Li atom
]
1 = [
    "{Li+}", # Li+
]

[Be]
0 = [
    "{Be/1}", # Be atom
]
2 = [
    "{Be+2}", # Be2+
]

[B]
0 = [
    "{Bv3}",
    "{B^1v2}",
    "{B/1v1}",
    "{B/1^1}", # B atom
]
-1 = ["{B-v4}"]

[C]
0 = [
    "{Cv4}",
    "{C^1v3}",
    "{C/1^2v2}",
    "{C/1v1}",
    "{C/1^2}",   # C atom
]
1 = ["{C+v3}"]
-1 = ["{C-/1v3}"]

[N]
0 = [
    "{N/1v3}",
    "{N/1^1v2}",
    "{N/2^2*3v1}",
    "{N/1^3}",     # N atom
]
1 = ["{N+v4}", "{N+/1v2}"]
-1 = ["{N-/2v2}"]
-3 = ["{N-3/4}"]

[O]
0 = [
    "{O/2v2}",
    "{O/2^1v1}",
    "{O/2^2}",   # O atom
]
1 = ["{O+/1v3}", "{O+/2v1}"]
-1 = ["{O-/3v1}"]
-2 = ["{O-2/4}"]

[F]
0 = [
    "{F/3v1}", # F2, HF, F-X
    "{F/3^1}", # F atom
]
-1 = [
    "{F-/4}", # F-
]

[Ne]
0 = [
    "{Ne/4}", # Ne atom
]

[Na]
0 = [
    "{Na^1}", # Na atom
]
1 = ["{Na+}"]

[Mg]
0 = [
    "{Mgv2}",
    "{Mg^1v1}",
    "{Mg/1}",   # Mg atom
]
2 = ["{Mg+2}"]

[Al]
0 = [
    "{Alv3}",
    "{Al/1^1}", # Al atom
]
3 = ["{Al+3}"]

[Si]
0 = [
    "{Siv4}",
    "{Siv2}",
    "{Si^1v3}",
    "{Si/1^2}", # Si atom
]

[P]
0 = [
    "{P/1v3}",
    "{Pv5}",
    "{P/1^3}", # P atom
]
1 = ["{P+v4}"]
-1 = ["{P-/2v3}"]

[S]
0 = [
    "{S/2v2}",
    "{S/2^1v1}",
    "{S/1v4}",
    "{Sv6}",
    "{S/2^2}",   # S atom
]
1 = ["{S+/1v3}"]
-1 = ["{S-/3v1}"]
-2 = ["{S-2/4}"]

[Cl]
0 = [
    "{Cl/3v1}", # HCl, Cl-X
    "{Clv3}",
    "{Clv5}",
    "{Cl/3^1}", # Cl atom
]
1 = [
    "{Cl+/2v2}", # Cl-Cl(+)-Cl (DOI: 10.1021/ic950305s)
    "{Cl+/3<2}", # Pyr->Cl(+)<-Pyr (DOI: 10.1071/CH13202)
]
-1 = ["{Cl-/4}"]

[Ar]
0 = [
    "{Ar/4}", # Ar atom
]

[K]
0 = [
    "{K^1}", # K atom
]
1 = ["{K+}"]

[Ca]
0 = [
    "{Ca/1}", # Ca atom
]
2 = ["{Ca+2}"]

# 3d

[Ga]
0 = [
    "{Ga/1^1}", # Ga atom
]

[Ge]
0 = [
    "{Ge/1^2}", # Ge atom
]

[As]
0 = [
    "{As/1^3}", # As atom
]

[Se]
0 = [
    "{Se/2v2}",
    "{Se/2^1v1}",
    "{Sev4}",
    "{Sev6}",
    "{Se/2^2}",   # Se atom
]
-1 = ["{Se-/3v1}"]
-2 = ["{Se-2/4}"]

[Br]
0 = [
    "{Br/3v1}",
    "{Br/3^1}",
    "{Brv3}",
    "{Brv5}",
    "{Br/3^1}", # Br atom
]
1 = [
    "{Br+/3}",     # Br+
    "{Br+/2^1v1}", # Br(+)-Br (DOI: 10.1021/ic50109a033, 10.1016/0301-0104(88)80004-1)
    "{Br+/2v2}",   # Br-Br(+)-Br, X-Br(+)-X  (DOI: 10.1021/ic950305s)
    "{Br+/3<2}",   # Pyr->Br(+)<-Pyr (DOI: 10.1071/CH13202)
]
-1 = ["{Br-/4}"]

[Kr]
0 = [
    "{Kr/4}",   # Kr atom
    "{Kr/3m2}", # KrF2
]
1 = [
    "{Kr+/3v1}",   # KrF+
    "{Kr+/3<1v1}", # FKrF->KrF+, HCN->KrF
]

[Rb]
0 = [
    "{Rb^1}", # Rb atom
]

[Sr]
0 = [
    "{Sr/1}", # Sr atom
]

# 4d

[In]
0 = [
    "{In/1^1}", # In atom
]

[Sn]
0 = [
    "{Sn/1^2}", # Sn atom
]

[Sb]
0 = [
    "{Sb/1^3}", # Sb atom
]

[Te]
0 = [
    "{Te/2^2}", # Te atom
]

[I]
0 = [
    "{I/3v1}",   # I2, I-X
    "{I/3H1}",   # HI
    "{I/3^1}",
    "{Iv3}",
    "{Iv5}",
    "{I/3v1m0}", # I-I*..I-I(+)-I (DOI: 10.1021/ic00224a009)
    "{I/3m1}",   # I-I..I*-I(+)-I (DOI: 10.1021/ic00224a009)
    "{I/3^1}",   # I atom
]
1 = [
    "{I+/3}",     # I+
    "{I+/2v2}",   # I-I(+)-I, X-I(+)-X  (DOI: 10.1021/ic950305s)
    "{I+/2^1v1}", # I(+)-I (DOI:10.1021/ic50043a024)
    "{I+/3<2}",   # Pyr->I(+)<-Pyr (DOI: 10.1071/CH13202)
    "{I+/2v1m1}", # I-I..I-I(+)-I  (DOI: 10.1021/ic00224a009)
]
-1 = [
    "{I-/4}", # I-
]

[Xe]
0 = [
    "{Xe/4}",      # Xe atom
    "{Xe/3m2}",    # XeF2, XeCl2, XeX2
    "{Xe/2m4}",    # XeF4, XeOF2
    "{Xe/1m6}",    # XeF6, XeOF4, XeO2F2, [HXeO4]-, [XeO3F]-
    "{Xe/1<v1m6}", # MeCN->XeO3
    "{Xem8}",      # XeO2F4, XeO3F2, XeO4, H4XeO6, [XeO6]3-, [XeO6]4-
]
1 = [
    "{Xe+/3v1}",     # XeF+, XeCl+, XeX+
    "{Xe+/3<1v1}",   # HF->XeF+, HCN->XeF+, MeCN->XeF+
    "{Xe+/2v1m2}",   # [XeF3]+, [XeF2X]+
    "{Xe+/1v1m4}",   # [XeF5]+, [XeOF3]+, XeO2F+
    "{Xe+/1<1v1m4}", # F5XeF->[XeF5]+
]
-1 = [
    "{Xe-/1v1m4}", # [XeF5]-
    "{Xe-v1m6}",   # [XeF7]-, [XeO2F3]-, [XeOF5]-
]
-2 = [
    "{Xe-2v2m6}", # [XeF8]2-
]

[Cs]
0 = [
    "{Cs^1}", # Cs atom
]

[Ba]
0 = [
    "{Ba/1}", # Ba atom
]

# 4f
# 5d

[Tl]
0 = [
    "{Tl/1^1}", # Tl atom
]

[Pb]
0 = [
    "{Pb/1^2}", # Pb atom
]

[Bi]
0 = [
    "{Bi/1^3}", # Bi atom
]

[Po]
0 = [
    "{Po/2^2}", # Po atom
]

[At]
0 = [
    "{At/3v1}", # At2
    "{At/3^1}", # At atom
]

[Rn]
0 = [
    "{Rn/4}",   # Rn atom
    "{Rn/3m2}", # RnF2
    "{Rn/2m4}", # RnF4
    "{Rn/1m6}", # RnF6, RnO3
]

[Fr]
0 = [
    "{Fr^1}", # Fr atom
]

[Ra]
0 = [
    "{Ra/1}", # Ra atom
]

# 5f
# 6d

[Nh]
0 = [
    "{Nh/1^1}", # Nd atom
]

[Fl]
0 = [
    "{Fl/1^2}", # Fl atom
]

[Mc]
0 = [
    "{Mc/1^3}", # Mc atom
]

[Lv]
0 = [
    "{Lv/2^2}", # Lv atom
]

[Ts]
0 = [
    "{Ts/3^1}", # Ts atom
]

[Og]
0 = [
    "{Og/4}", # Og atom   
]
