[package]
name = "umol-models-valence"
version = "0.1.0"
authors = ["Dmitrij Rappoport <dmitrij@rappoport.org>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rappoport/umol"
keywords = ["chemistry", "cheminformatics", "molecular parsing"]
edition = "2021"

[dependencies]
indexmap = "2.11.1"
map-macro = "0.3.0"
petgraph = "0.8.2"
regex = "1.11.2"
serde = { version = "1.0.223", features = ["derive"] }
serde_json = "1.0.145"
umol = { path = "../umol" }
umol-data = { path = "../umol-data" }
umol-macros = { path = "../umol-macros" }

[dev-dependencies]
rstest = "0.26.1"

[lib]
bench = false
