[package]
name = "umol-edn-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
libfuzzer-sys = "0.4"
umol-edn = { path = "..", features = ["serde"] }

[[bin]]
name = "fuzz_parse"
path = "fuzz_targets/fuzz_parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_parse_all"
path = "fuzz_targets/fuzz_parse_all.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_deser"
path = "fuzz_targets/fuzz_deser.rs"
test = false
doc = false
bench = false
