[package]
name = "umol"
version = "0.1.0"
authors = ["Dmitrij Rappoport <dmitrij@rappoport.org>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rappoport/umol"
keywords = [
    "chemistry",
    "cheminformatics",
    "computational chemistry",
    "molecular modeling",
    "molecular representation",
]
description = "Rust-based computational chemistry library."

[dependencies]
map-macro = "0.3.0"
serde = { version = "1.0.221", features = ["derive"] }
serde_json = "1.0.145"
slog = "2.7.0"
slog-async = "2.8.0"
slog-envlogger = "2.2.0"
slog-term = "2.9.2"
thiserror = "2.0"
umol-macros = { path = "../umol-macros", version = "0.1.0" }

[dev-dependencies]
rstest = "0.26.1"
pretty_assertions = "1.4.1"

[lib]
bench = false
