[package]
name = "umol"
version = "0.1.0"
authors = ["Dmitrij Rappoport <dmitrij@rappoport.org>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rappoport/umol"
keywords = [
    "chemistry",
    "cheminformatics",
    "computational chemistry",
    "molecular modeling",
    "molecular representation",
]
description = "Rust-based computational chemistry library."

[dependencies]

[dev-dependencies]
rstest = "0.26.1"
pretty_assertions = "1.4.1"

[lib]
bench = false
