//! Tests for MOL file parsing
use rstest::*;

use crate::io::ctfile::config::{CtabParseFlags, CtfileIoConfig};
use crate::io::ctfile::parser::{
    has_extended_features, parse_extended_mol, parse_extended_mol_bytes, parse_extended_mol_with,
    parse_mol, parse_mol_bytes, parse_mol_with,
};

#[fixture]
fn methane_mol() -> &'static str {
    "Methane\nRDKit          3D\nGenerated by RDKit\n  1  0  0  0  0  0  0  0  0  0999 V2000\n    1.2345    2.3456    3.4567 C   0  0  0  0  0  0  0  0  0  0  0  0\nM  END\n"
}

#[fixture]
fn ethane_mol() -> &'static [u8] {
    b"Ethane\nRDKit          3D\nGenerated by RDKit\n  2  1  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.5400    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0  0  0  0\nM  END\n"
}

#[fixture]
fn chiral_mol() -> &'static str {
    "Chiral\n\n\n  1  0  0  0  1  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\nM  END\n"
}

#[fixture]
fn ethane_mol_with_data() -> &'static [u8] {
    b"Ethane\nRDKit          3D\nGenerated by RDKit\n  2  1  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.5400    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0  0  0  0\nM  END\n>  <Name>\nEthane\n\n>  <Formula>\nC2H6\n\n$$$$\n"
}

#[fixture]
fn query_mol() -> &'static [u8] {
    b"Query\nRDKit          3D\nWith query atom\n  1  0  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0\nM  END\n"
}

#[fixture]
fn empty_header_mol() -> &'static str {
    "\n\n\n  1  0  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\nM  END\n"
}

#[fixture]
fn methane_unicode_whitespace_mol() -> &'static [u8] {
    b"Methane\nRDKit          3D\nGenerated by RDKit\n  1  0  0  0  0  0  0  0  0  0999 V2000\n \xc2\xa0  1.2345\xc2\xa0   2.3456    3.4567 C   0  0  0  0  0  0  0  0  0  0  0  0\nM  END\n"
}

#[rstest]
fn test_parse_mol(ethane_mol: &[u8]) {
    let result = parse_mol_bytes(ethane_mol);
    assert!(result.is_ok(), "should have succeeded: {:?}", result.err());

    let molecule = result.unwrap();
    assert_eq!(molecule.atom_count(), 2, "should have 2 atoms");
    assert_eq!(molecule.bond_count(), 1, "should have 1 bond");
}

#[rstest]
fn test_parse_trailing_data_fields(ethane_mol_with_data: &[u8]) {
    let result = parse_mol_bytes(ethane_mol_with_data);
    assert!(result.is_ok(), "Molecule parser should parse SDF files");
    let molecule = result.unwrap();
    assert_eq!(molecule.atom_count(), 2, "Should parse 2 atoms");
    assert_eq!(molecule.bond_count(), 1, "Should parse 1 bond");
}

#[rstest]
fn test_parse_mol_chiral_flag(chiral_mol: &str) {
    let result = parse_mol(chiral_mol);
    assert!(result.is_ok(), "Should parse: {:?}", result.err());
    let molecule = result.unwrap();
    assert_eq!(
        molecule.properties.get("chiral_flag"),
        Some(&"true".to_string()),
        "Chiral flag property should be 'true'"
    );
}

#[rstest]
fn test_parse_mol_str(methane_mol: &str) {
    let result = parse_mol(methane_mol);
    assert!(
        result.is_ok(),
        "parse_mol should succeed: {:?}",
        result.err()
    );
    let molecule = result.unwrap();
    assert_eq!(molecule.atom_count(), 1);
    assert_eq!(molecule.comments.len(), 3);
    assert_eq!(molecule.comments[0], "Methane");
}

#[rstest]
fn test_parse_mol_with_config(methane_mol: &str) {
    let config = CtfileIoConfig::basic_max();
    let result = parse_mol_with(methane_mol, &config);
    assert!(
        result.is_ok(),
        "parse_mol_with should succeed: {:?}",
        result.err()
    );
    let molecule = result.unwrap();
    assert_eq!(molecule.atom_count(), 1);
}

#[rstest]
fn test_parse_mol_header_in_comments(methane_mol: &str) {
    let result = parse_mol(methane_mol).unwrap();
    assert_eq!(
        result.comments[0], "Methane",
        "First comment should be molecule name"
    );
    assert_eq!(
        result.comments[1], "RDKit          3D",
        "Second comment should be program info"
    );
    assert_eq!(
        result.comments[2], "Generated by RDKit",
        "Third comment should be comment line"
    );
}

#[rstest]
fn test_parse_mol_empty_header(empty_header_mol: &str) {
    let result = parse_mol(empty_header_mol);
    assert!(
        result.is_ok(),
        "Should parse MOL with empty header: {:?}",
        result.err()
    );
    let molecule = result.unwrap();
    assert_eq!(molecule.comments[0], "");
    assert_eq!(molecule.comments[1], "");
    assert_eq!(molecule.comments[2], "");
}

#[rstest]
fn test_parse_mol_invalid_query_features(query_mol: &[u8]) {
    let result = parse_mol_bytes(query_mol);
    assert!(
        result.is_err(),
        "Molecule parser should fail on query atoms"
    );

    let error = result.unwrap_err();
    let error_string = format!("{}", error);
    assert!(
        error_string.contains("Format error")
            || error_string.contains("Parse error")
            || error_string.contains("Invalid atom line"),
        "Error should mention parsing failure: {}",
        error_string
    );
}

#[rstest]
fn test_parse_mol_invalid_unicode(methane_unicode_whitespace_mol: &[u8]) {
    let result = parse_mol_bytes(methane_unicode_whitespace_mol);
    assert!(
        result.is_err(),
        "Should fail parsing MOL with unicode whitespace without UNICODE flag"
    );
}

#[rstest]
fn test_parse_mol_lenient(methane_unicode_whitespace_mol: &[u8]) {
    let config =
        CtfileIoConfig::with_parse_flags(CtabParseFlags::BASIC_MAX & CtabParseFlags::LENIENT);
    let result = parse_mol_with(
        std::str::from_utf8(methane_unicode_whitespace_mol).unwrap(),
        &config,
    );
    assert!(
        result.is_ok(),
        "Should parse MOL with nbsp when UNICODE flag is set: {:?}",
        result.err()
    );
    let molecule = result.unwrap();
    assert_eq!(molecule.atoms.len(), 1);
}

#[rstest]
fn test_parse_extended_mol(methane_mol: &str) {
    let result = parse_extended_mol(methane_mol);
    assert!(result.is_ok(), "should have succeeded: {:?}", result.err());

    let molecule = result.unwrap();
    assert!(
        !has_extended_features(&molecule),
        "should not have query features"
    );
    assert_eq!(molecule.atom_count(), 1, "should have 1 atom");
    assert_eq!(molecule.bond_count(), 0, "should have 0 bonds");
}

#[rstest]
fn test_parse_extended_mol_str(methane_mol: &str) {
    let result = parse_extended_mol(methane_mol);
    assert!(
        result.is_ok(),
        "parse_extended_mol should succeed: {:?}",
        result.err()
    );
    let molecule = result.unwrap();
    assert_eq!(molecule.atom_count(), 1);
    assert_eq!(molecule.comments.len(), 3);
    assert_eq!(molecule.comments[0], "Methane");
}

#[rstest]
fn test_parse_extended_mol_with_config(methane_mol: &str) {
    let config = CtfileIoConfig::extended();
    let result = parse_extended_mol_with(methane_mol, &config);
    assert!(
        result.is_ok(),
        "parse_extended_mol_with should succeed: {:?}",
        result.err()
    );
    let molecule = result.unwrap();
    assert_eq!(molecule.atom_count(), 1);
}

#[rstest]
fn test_parse_extended_mol_trailing_data_fields(ethane_mol_with_data: &[u8]) {
    let result_extended = parse_extended_mol_bytes(ethane_mol_with_data);
    assert!(
        result_extended.is_ok(),
        "Extended parser should parse SDF files"
    );
    let molecule_extended = result_extended.unwrap();
    assert_eq!(molecule_extended.atom_count(), 2, "Should parse 2 atoms");
    assert_eq!(molecule_extended.bond_count(), 1, "Should parse 1 bond");
}

#[rstest]
fn test_parse_extended_mol_chiral_flag(chiral_mol: &str) {
    let result = parse_extended_mol(chiral_mol);
    assert!(result.is_ok(), "Should parse: {:?}", result.err());
    let molecule = result.unwrap();
    assert_eq!(
        molecule.properties.get("chiral_flag"),
        Some(&"true".to_string()),
        "Chiral flag property should be 'true'"
    );
}
