//! Tests for SDF file parsing

use rstest::*;

use crate::io::ctfile::config::CtfileIoConfig;
use crate::io::ctfile::parser::{
    parse_extended_sdf, parse_extended_sdf_iter, parse_extended_sdf_with, parse_sdf,
    parse_sdf_bytes, parse_sdf_iter, parse_sdf_with,
};

#[fixture]
fn single_compound_sdf() -> &'static str {
    "Methane\nRDKit          3D\nGenerated by RDKit\n  1  0  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\nM  END\n> <Name>\nMethane\n\n> <MW>\n16.04\n\n$$$$\n"
}

#[fixture]
fn two_compound_sdf() -> &'static str {
    "Methane\nRDKit          3D\nGenerated by RDKit\n  1  0  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\nM  END\n> <Name>\nMethane\n\n$$$$\nEthane\nRDKit          3D\nGenerated by RDKit\n  2  1  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.5400    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0  0  0  0\nM  END\n> <Name>\nEthane\n\n$$$$\n"
}

#[rstest]
fn test_parse_sdf_str(single_compound_sdf: &str) {
    let result = parse_sdf(single_compound_sdf);
    assert!(
        result.is_ok(),
        "parse_sdf should succeed: {:?}",
        result.err()
    );
    let molecules = result.unwrap();
    assert_eq!(molecules.len(), 1);
    assert_eq!(molecules[0].atom_count(), 1);
}

#[rstest]
fn test_parse_sdf_bytes(single_compound_sdf: &str) {
    let result = parse_sdf_bytes(single_compound_sdf.as_bytes());
    assert!(
        result.is_ok(),
        "parse_sdf_bytes should succeed: {:?}",
        result.err()
    );
    let molecules = result.unwrap();
    assert_eq!(molecules.len(), 1);
}

#[rstest]
fn test_parse_sdf_with_config(single_compound_sdf: &str) {
    let config = CtfileIoConfig::basic_max();
    let result = parse_sdf_with(single_compound_sdf, &config);
    assert!(
        result.is_ok(),
        "parse_sdf_with should succeed: {:?}",
        result.err()
    );
    let molecules = result.unwrap();
    assert_eq!(molecules.len(), 1);
}

#[rstest]
fn test_parse_sdf_multiple_compounds(two_compound_sdf: &str) {
    let result = parse_sdf(two_compound_sdf);
    assert!(
        result.is_ok(),
        "parse_sdf should succeed: {:?}",
        result.err()
    );
    let molecules = result.unwrap();
    assert_eq!(molecules.len(), 2);
    assert_eq!(molecules[0].atom_count(), 1);
    assert_eq!(molecules[1].atom_count(), 2);
    assert_eq!(molecules[1].bond_count(), 1);
}

#[rstest]
fn test_parse_sdf_properties(single_compound_sdf: &str) {
    let result = parse_sdf(single_compound_sdf).unwrap();
    let molecule = &result[0];
    assert_eq!(molecule.properties.len(), 2);
    assert_eq!(
        molecule.properties.get("Name"),
        Some(&"Methane".to_string())
    );
    assert_eq!(molecule.properties.get("MW"), Some(&"16.04".to_string()));
}

#[rstest]
fn test_parse_sdf_comments(single_compound_sdf: &str) {
    let result = parse_sdf(single_compound_sdf).unwrap();
    let molecule = &result[0];
    assert_eq!(molecule.comments.len(), 3);
    assert_eq!(molecule.comments[0], "Methane");
}

#[rstest]
fn test_parse_extended_sdf_str(single_compound_sdf: &str) {
    let result = parse_extended_sdf(single_compound_sdf);
    assert!(
        result.is_ok(),
        "parse_extended_sdf should succeed: {:?}",
        result.err()
    );
    let molecules = result.unwrap();
    assert_eq!(molecules.len(), 1);
}

#[rstest]
fn test_parse_extended_sdf_with_config(single_compound_sdf: &str) {
    let config = CtfileIoConfig::extended();
    let result = parse_extended_sdf_with(single_compound_sdf, &config);
    assert!(
        result.is_ok(),
        "parse_extended_sdf_with should succeed: {:?}",
        result.err()
    );
    let molecules = result.unwrap();
    assert_eq!(molecules.len(), 1);
}

#[rstest]
fn test_parse_sdf_iter(single_compound_sdf: &str) {
    let iter = parse_sdf_iter(single_compound_sdf.as_bytes());
    let molecules: Vec<_> = iter.collect();
    assert_eq!(molecules.len(), 1);
    assert!(molecules[0].is_ok());
    assert_eq!(molecules[0].as_ref().unwrap().atom_count(), 1);
}

#[rstest]
fn test_parse_sdf_iter_multiple(two_compound_sdf: &str) {
    let iter = parse_sdf_iter(two_compound_sdf.as_bytes());
    let molecules: Vec<_> = iter.collect();
    assert_eq!(molecules.len(), 2);
    assert!(molecules[0].is_ok());
    assert!(molecules[1].is_ok());
}

#[rstest]
fn test_parse_extended_sdf_iter(single_compound_sdf: &str) {
    let iter = parse_extended_sdf_iter(single_compound_sdf.as_bytes());
    let molecules: Vec<_> = iter.collect();
    assert_eq!(molecules.len(), 1);
    assert!(molecules[0].is_ok());
}
