use std::path::Path;
use std::{env, fs};

use lalrpop;
use walkdir::WalkDir;

fn main() {
    generate_smiles_parser();
    generate_compliance_tests();
}

fn generate_smiles_parser() {
    let in_dir = "src/io/smiles/parser";
    // Rebuild if any file in the parser directory changes (including new files)
    println!("cargo:rerun-if-changed={}", in_dir);
    for entry in fs::read_dir(in_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().unwrap() == "lalrpop" {
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }
    lalrpop::Configuration::new()
        .log_debug()
        .emit_report(true)
        .set_in_dir(in_dir)
        .process()
        .unwrap();
}

fn generate_compliance_tests() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("generated_tests.rs");

    let mut generated_code = String::new();

    // Add imports needed for the generated tests
    generated_code.push_str("// AUTO-GENERATED - DO NOT EDIT\n");
    generated_code.push_str("// Generated by build.rs based on actual directory contents\n\n");

    // Discover what actually exists in the organized data directories
    let data_path = "tests/mol_parsing/data";

    for category in ["molecule", "moleculelike", "invalid"] {
        let category_path = format!("{}/{}", data_path, category);

        if let Ok(entries) = fs::read_dir(&category_path) {
            for entry in entries {
                if let Ok(entry) = entry {
                    let source_name = entry.file_name().to_string_lossy().to_string();
                    let source_path = format!("{}/{}", category_path, source_name);

                    // Check if this source/category combo has .mol files
                    let has_files = WalkDir::new(&source_path).into_iter().any(|e| {
                        e.map(|entry| entry.path().extension().map_or(false, |ext| ext == "mol"))
                            .unwrap_or(false)
                    });

                    if has_files {
                        let source_ident = source_name.replace('-', "_");

                        // Generate tests for parse_mol
                        let mol_should_succeed = category == "molecule";
                        generated_code.push_str(&format!(
                            r#"#[rstest]
fn test_parse_mol_{}_{source_ident}(
    #[files("{source_path}/*.mol")] file_path: PathBuf,
) {{
    run_parse_mol_test(&file_path, {mol_should_succeed});
}}

"#,
                            category,
                            source_path = source_path,
                            mol_should_succeed = mol_should_succeed
                        ));

                        // Generate tests for parse_mol_moleculelike
                        let moleculelike_should_succeed = category != "invalid";
                        generated_code.push_str(&format!(
                            r#"#[rstest]
fn test_parse_mol_moleculelike_{}_{source_ident}(
    #[files("{source_path}/*.mol")] file_path: PathBuf,
) {{
    run_parse_mol_moleculelike_test(&file_path, {moleculelike_should_succeed});
}}

"#,
                            category,
                            source_path = source_path,
                            moleculelike_should_succeed = moleculelike_should_succeed
                        ));
                    }
                }
            }
        }
    }

    // Write the generated code
    fs::write(&dest_path, generated_code).unwrap();

    // Rebuild if the data directory structure changes
    println!("cargo:rerun-if-changed=tests/mol_parsing/data");

    // Also rebuild if the source data changes
    println!("cargo:rerun-if-changed=tests/mol_parsing/data_raw");
}
