[package]
name = "umol-models-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = { version = "2.4.0", features = ["serde"] }
bstr = "1.9"
float-cmp = "0.10"
num-traits = "0.2.19"
nalgebra = { version = "0.33", features = ["serde-serialize"] }
nom = { version = "8.0.0" }
num = "0.4.3"
petgraph = { version = "0.8.1", features = ["stable_graph", "serde-1"] }
serde = { version = "1.0", features = ["derive"] }
umol = { path = "../umol" }
umol-data = { path = "../umol-data" }
fast-float = "0.2.0"
smallvec = "1.15.1"

[dev-dependencies]
rstest = "0.26"
pretty_assertions = "1.4.0"
criterion = "0.7"
insta = { version = "1.31", features = ["yaml", "glob"] }
serde_yaml = "0.9"
serde_json = "1.0"
tempfile = "3.0"
walkdir = "2.0"

[[bench]]
name = "parsing_bench"
harness = false
