//! Serialization tests for core types

use umol_models_graph::io::ctab::molecule::{Header, MoleculeStandard};
use umol_models_graph::io::ctab::atom::{AtomStandard, AtomRadical};
use umol_models_graph::io::ctab::bond::{BondStandard, BondType};
use umol_data::Element;
use petgraph::stable_graph::StableGraph;
use petgraph::Undirected;
use std::collections::{BTreeMap, HashMap};

#[test]
fn test_header_serialization() {
    let header = Header::new(
        "Test Molecule".to_string(),
        "Generated by test".to_string(),
        "Test comment".to_string(),
    );
    
    // Test YAML serialization
    let yaml = serde_yaml::to_string(&header).expect("Failed to serialize Header to YAML");
    println!("Header YAML:\n{}", yaml);
    
    let deserialized: Header = serde_yaml::from_str(&yaml).expect("Failed to deserialize Header from YAML");
    assert_eq!(header, deserialized);
    
    // Test JSON serialization 
    let json = serde_json::to_string_pretty(&header).expect("Failed to serialize Header to JSON");
    println!("Header JSON:\n{}", json);
    
    let deserialized: Header = serde_json::from_str(&json).expect("Failed to deserialize Header from JSON");
    assert_eq!(header, deserialized);
}

#[test]
fn test_atom_standard_serialization() {
    let mut atom = AtomStandard::new(Element::C);
    atom.charge = -1;
    atom.radical = Some(AtomRadical::Doublet);
    atom.hydrogen_count = Some(3);
    // Test position serialization with nalgebra Point3D
    atom.position = Some(nalgebra::Point3::new(1.5, -2.3, 0.8));
    
    // Test YAML serialization
    let yaml = serde_yaml::to_string(&atom).expect("Failed to serialize AtomStandard to YAML");
    println!("AtomStandard YAML:\n{}", yaml);
    
    let deserialized: AtomStandard = serde_yaml::from_str(&yaml).expect("Failed to deserialize AtomStandard from YAML");
    assert_eq!(atom.element, deserialized.element);
    assert_eq!(atom.charge, deserialized.charge);
    assert_eq!(atom.radical, deserialized.radical);
    assert_eq!(atom.hydrogen_count, deserialized.hydrogen_count);
    assert_eq!(atom.position, deserialized.position);
}

#[test]
fn test_bond_standard_serialization() {
    let mut bond = BondStandard::new(BondType::Double);
    bond.properties.insert("test_key".to_string(), "test_value".to_string());
    
    // Test YAML serialization
    let yaml = serde_yaml::to_string(&bond).expect("Failed to serialize BondStandard to YAML");
    println!("BondStandard YAML:\n{}", yaml);
    
    let deserialized: BondStandard = serde_yaml::from_str(&yaml).expect("Failed to deserialize BondStandard from YAML");
    assert_eq!(bond.bond_type, deserialized.bond_type);
    assert_eq!(bond.properties, deserialized.properties);
}

#[test]
fn test_molecule_standard_serialization() {
    let header = Header::new("Test".to_string(), "Test".to_string(), "Test".to_string());
    let graph = StableGraph::<AtomStandard, BondStandard, Undirected, usize>::with_capacity(0, 0);
    let sgroups = BTreeMap::new();
    let properties = HashMap::new();
    
    let molecule = MoleculeStandard {
        graph,
        sgroups,
        properties,
        header,
    };
    
    // Test YAML serialization
    let yaml = serde_yaml::to_string(&molecule).expect("Failed to serialize MoleculeStandard to YAML");
    println!("MoleculeStandard YAML:\n{}", yaml);
    
    let deserialized: MoleculeStandard = serde_yaml::from_str(&yaml).expect("Failed to deserialize MoleculeStandard from YAML");
    assert_eq!(molecule.header, deserialized.header);
    assert_eq!(molecule.properties, deserialized.properties);
}

#[test]
fn test_nalgebra_point3d_serialization() {
    use nalgebra::Point3;
    
    let point = Point3::new(1.5, -2.3, 0.8);
    
    // Test YAML serialization of nalgebra Point3D
    let yaml = serde_yaml::to_string(&point).expect("Failed to serialize Point3D to YAML");
    println!("Point3D YAML:\n{}", yaml);
    
    let deserialized: Point3<f64> = serde_yaml::from_str(&yaml).expect("Failed to deserialize Point3D from YAML");
    assert_eq!(point, deserialized);
    
    // Test JSON serialization of nalgebra Point3D
    let json = serde_json::to_string_pretty(&point).expect("Failed to serialize Point3D to JSON");
    println!("Point3D JSON:\n{}", json);
    
    let deserialized: Point3<f64> = serde_json::from_str(&json).expect("Failed to deserialize Point3D from JSON");
    assert_eq!(point, deserialized);
}

#[test]
fn test_insta_snapshot_integration() {
    use insta::assert_yaml_snapshot;
    
    let header = Header::new(
        "Caffeine".to_string(),
        "Generated for testing".to_string(),
        "C8H10N4O2".to_string(),
    );
    
    // Test that insta can create snapshots of our serializable types
    assert_yaml_snapshot!("header_caffeine", &header);
}
