[package]
name = "umol-geometric-graph"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords = ["chemistry", "cheminformatics", "molecules", "geometry", "graph"]
description = "Conversions between the geometric and graph molecular models for umol."

[lib]
bench = false

[dependencies]
umol-graph-ir = { path = "../umol-graph-ir", version = "0.7.0" }
umol-chem = { path = "../umol-chem", version = "0.7.0" }
umol-geometric = { path = "../umol-geometric", version = "0.7.0" }
umol-params = { path = "../umol-params", version = "0.7.0" }

[dev-dependencies]
pretty_assertions = "1.4.1"
rstest = "0.26.1"

[lints.clippy]
absolute_paths = "warn"
mod_module_files = "warn"
