[package]
name = "umol-msym"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Ergonomic Rust wrapper for libmsym (molecular symmetry)."
license = "MIT"
repository.workspace = true
readme.workspace = true
keywords = ["chemistry", "molecules", "symmetry", "libmsym"]

[dependencies]
umol-msym-sys = { path = "../umol-msym-sys", version = "0.6.0" }
nalgebra = "0.34.0"
thiserror = "2"

[dev-dependencies]
rand = "0.9"
rand_chacha = "0.9"
rstest = "0.26.1"

[lints.clippy]
absolute_paths = "warn"
mod_module_files = "warn"
