[package]
name = "umol-models"
version = "0.1.0"
authors = ["Dmitrij Rappoport <dmitrij@rappoport.org>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rappoport/umol"
keywords = ["chemistry", "cheminformatics", "molecular parsing"]

[dependencies]
umol = { path = "../umol" }
umol-data = { path = "../umol-data" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
map-macro = "0.3.0"
nom = "8.0.0"