//! Header parser and types for MOL files.

use bstr::ByteSlice;
use nom::character::complete::{line_ending, not_line_ending};
use nom::combinator::map;
use nom::sequence::terminated;
use nom::{error, Parser};
use serde::{Deserialize, Serialize};

/// MOL file header information (3 lines)
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Header {
    pub name: String,         // Molecule title / name (line 1)
    pub program_info: String, // Program info (line 2)
    pub comment: String,      // Comment (line 3)
}

impl Header {
    /// Create a new header
    pub fn new(name: String, program_info: String, comment: String) -> Self {
        Self {
            name,
            program_info,
            comment,
        }
    }
}

/// Parse a single line from the MOL header
pub(super) fn header_input<'a>() -> impl Parser<&'a [u8], Output = String, Error = error::Error<&'a [u8]>>
{
    map(not_line_ending, |s: &[u8]| s.to_str_lossy().into_owned())
}

/// Parse the 3-line MOL file header (title, program info, comment)
pub(crate) fn header<'a>() -> impl Parser<&'a [u8], Output = Header, Error = error::Error<&'a [u8]>> {
    map(
        (
            terminated(header_input(), line_ending),
            terminated(header_input(), line_ending),
            terminated(header_input(), line_ending),
        ),
        |(name, program_info, comment)| Header::new(name, program_info, comment),
    )
}

#[cfg(test)]
mod tests {
    use nom::combinator::all_consuming;
    use rstest::*;

    use super::*;

    #[rstest]
    #[case(
        b"Caffeine\nRDKit          3D\nGenerated by RDKit\n",
        "valid",
        Header::new("Caffeine".to_string(), "RDKit          3D".to_string(), "Generated by RDKit".to_string())
    )]
    #[case(b"\n\n\n", "empty", Header::new("".to_string(), "".to_string(), "".to_string()))]
    #[case(
        b"  Molecule Name  \n  Program Info  \n  Comment Line  \n",
        "whitespace",
        Header::new("  Molecule Name  ".to_string(), "  Program Info  ".to_string(), "  Comment Line  ".to_string())
    )]
    fn test_header(#[case] input: &[u8], #[case] desc: &str, #[case] expected: Header) {
        let result = all_consuming(header()).parse(input);
        assert!(result.is_ok(), "{} should have succeeded", desc);
        let (remaining, header) = result.unwrap();
        assert!(remaining.is_empty(), "{} has remaining data", desc);
        assert_eq!(header.name, expected.name);
        assert_eq!(header.program_info, expected.program_info);
        assert_eq!(header.comment, expected.comment);
    }
}
