use super::*;
use rstest::*;

#[test]
fn test_footer_empty() {
    let result = footer().parse(b"");
    assert!(result.is_ok());
    let (remaining, _) = result.unwrap();
    assert!(remaining.is_empty());
}

#[test]
fn test_footer_whitespace() {
    let result = footer().parse(b"\n\n  \t\n");
    assert!(result.is_ok());
    let (remaining, _) = result.unwrap();
    assert!(remaining.is_empty());
}

#[test]
fn test_footer_sdf_delimiter() {
    let result = footer().parse(b"\n$$$$\n");
    assert!(result.is_ok());
    let (remaining, _) = result.unwrap();
    assert!(remaining.is_empty());
}

#[test]
fn test_footer_sdf_delimiter_with_whitespace() {
    let result = footer().parse(b"\n\n$$$$\n  \n");
    assert!(result.is_ok());
    let (remaining, _) = result.unwrap();
    assert!(remaining.is_empty());
}

#[test]
fn test_parse_mol_file() {
    // Test parsing complete MOL file with header extraction
    let mol_content = b"Ethane\nRDKit\nTest molecule\n  2  1  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0  0  0  0\nM  END\n";
    let result = parse_mol_file(mol_content);
    assert!(
        result.is_ok(),
        "Complete MOL file should parse successfully"
    );

    let mol_file = result.unwrap();
    // Check header
    assert_eq!(mol_file.header.name, "Ethane");
    assert_eq!(mol_file.header.program_info, "RDKit");
    assert_eq!(mol_file.header.comment, "Test molecule");

    // Check molecule
    assert_eq!(mol_file.molecule.graph.node_count(), 2);
    assert_eq!(mol_file.molecule.graph.edge_count(), 1);
}

#[test]
fn test_has_query_features() {
    // Test standard molecule
    let standard_mol = b"Methane\nRDKit          3D\nGenerated by RDKit\n  1  0  0  0  0  0  0  0  0  0999 V2000\n    1.2345    2.3456    3.4567 C  -2  3  0  0  0  4  0  0  0  0  0  0\nM  END\n";
    let molecule = parse_mol(standard_mol).unwrap();
    assert!(
        !has_nonstandard_features(&molecule),
        "Standard molecule should not have query features"
    );

    // Test simple ethane molecule
    let ethane_mol = b"Ethane\nRDKit\nTest molecule\n  2  1  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0  0  0  0\nM  END\n";
    let molecule2 = parse_mol(ethane_mol).unwrap();
    assert!(
        !has_nonstandard_features(&molecule2),
        "Simple ethane should not have query features"
    );
}

#[rstest]
#[case(b"Methane\nRDKit          3D\nGenerated by RDKit\n  1  0  0  0  0  0  0  0  0  0999 V2000\n    1.2345    2.3456    3.4567 C  -2  3  0  0  0  4  0  0  0  0  0  0\nM  END\n",
       "valid")]
fn test_parse_mol(#[case] mol_str: &[u8], #[case] desc: &str) {
    let result = parse_mol(mol_str);
    assert!(
        result.is_ok(),
        "{} should have succeeded: {:?}",
        desc,
        result.err()
    );

    let molecule = result.unwrap();
    assert!(
        !has_nonstandard_features(&molecule),
        "{} should not have query features",
        desc
    );

    assert_eq!(molecule.atom_count(), 1, "{} should have 1 atom", desc);
    assert_eq!(molecule.bond_count(), 0, "{} should have 0 bonds", desc);
}

#[rstest]
#[case(b"Ethane\nRDKit          3D\nGenerated by RDKit\n  2  1  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.5400    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0  0  0  0\nM  END\n",
      "standard ethane")]
fn test_parse_mol_standard(#[case] mol_str: &[u8], #[case] desc: &str) {
    let result = parse_mol_standard(mol_str);
    assert!(
        result.is_ok(),
        "{} should have succeeded: {:?}",
        desc,
        result.err()
    );

    let molecule = result.unwrap();
    assert_eq!(molecule.atom_count(), 2, "{} should have 2 atoms", desc);
    assert_eq!(molecule.bond_count(), 1, "{} should have 1 bond", desc);
}

#[rstest]
#[case(b"Ethane\nRDKit\nTest molecule\n  2  1  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0  0  0  0\nM  END\n",
      "standard ethane")]
fn test_parse_mol_file_standard(#[case] mol_str: &[u8], #[case] desc: &str) {
    let result = parse_mol_file_standard(mol_str);
    assert!(
        result.is_ok(),
        "{} should have succeeded: {:?}",
        desc,
        result.err()
    );
}

#[test]
fn test_parse_mol_standard_query() {
    // MOL with query atom 'A' (any atom)
    let query_mol = b"Query\nRDKit          3D\nWith query atom\n  1  0  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0\nM  END\n";

    let result = parse_mol_standard(query_mol);
    assert!(
        result.is_err(),
        "Standard parser should fail on query atoms"
    );

    let error = result.unwrap_err();
    let error_string = format!("{}", error);
    assert!(
        error_string.contains("MOL parsing failed")
            || error_string.contains("Standard MOL parsing failed"),
        "Error should mention parsing failure: {}",
        error_string
    );
}

#[test]
fn test_progressive_parser_standard() {
    let mol = b"MyMol\n\nComment\n  1  0  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0\nM  END\n";
    let result = parse_mol_progressive_standard(mol);
    assert!(matches!(result[0], ParsedMolStandardLine::Header(_)));
    assert!(matches!(result[1], ParsedMolStandardLine::Header(_)));
    assert!(matches!(result[2], ParsedMolStandardLine::Header(_)));
    assert!(matches!(result[3], ParsedMolStandardLine::Counts(_)));
    assert!(matches!(result[4], ParsedMolStandardLine::Atom(_)));
    assert!(matches!(result[5], ParsedMolStandardLine::End));
}

#[test]
fn test_progressive_parser_alias() {
    let mol_with_alias = b"MyMol\n\n\n  1  0  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0\nA    1\nCF3\nM  END\n";
    let result = parse_mol_progressive(mol_with_alias);
    assert!(
        matches!(
            result[5],
            ParsedMolLine::Property(PropertyEntries::AtomAliasEntry(_))
        ),
        "Failed to parse two-line atom alias. Got: {:?}",
        result[5]
    );
}

#[test]
fn test_progressive_parser_legacy_list() {
    let mol_with_legacy = b"MyMol\n\n\n  1  0  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0\n  1 F    2   6   8\nM  END\n";
    let result = parse_mol_progressive(mol_with_legacy);
    assert!(
        matches!(
            result[5],
            ParsedMolLine::Property(PropertyEntries::AtomListEntry(_))
        ),
        "Failed to parse legacy atom list. Got: {:?}",
        result[5]
    );
}
