use super::*;
use rstest::*;

#[test]
fn test_footer_empty() {
    let result = footer().parse(b"");
    assert!(result.is_ok());
    let (remaining, _) = result.unwrap();
    assert!(remaining.is_empty());
}

#[test]
fn test_footer_whitespace() {
    let result = footer().parse(b"\n\n  \t\n");
    assert!(result.is_ok());
    let (remaining, _) = result.unwrap();
    assert!(remaining.is_empty());
}

#[test]
fn test_footer_sdf_delimiter() {
    let result = footer().parse(b"\n$$$$\n");
    assert!(result.is_ok());
    let (remaining, _) = result.unwrap();
    assert!(remaining.is_empty());
}

#[test]
fn test_footer_sdf_delimiter_with_whitespace() {
    let result = footer().parse(b"\n\n$$$$\n  \n");
    assert!(result.is_ok());
    let (remaining, _) = result.unwrap();
    assert!(remaining.is_empty());
}

#[test]
fn test_has_query_features() {
    let mol = b"Methane\nRDKit          3D\nGenerated by RDKit\n  1  0  0  0  0  0  0  0  0  0999 V2000\n    1.2345    2.3456    3.4567 C  -2  3  0  0  0  4  0  0  0  0  0  0\nM  END\n";
    let molecule = parse_mol_moleculelike(mol).unwrap();
    assert!(
        !has_nonstandard_features(&molecule),
        "Standard molecule should not have query features"
    );
}

#[rstest]
#[case(b"Methane\nRDKit          3D\nGenerated by RDKit\n  1  0  0  0  0  0  0  0  0  0999 V2000\n    1.2345    2.3456    3.4567 C  -2  3  0  0  0  4  0  0  0  0  0  0\nM  END\n",
       "valid")]
fn test_parse_mol_moleculelike(#[case] mol_str: &[u8], #[case] desc: &str) {
    let result = parse_mol_moleculelike(mol_str);
    assert!(
        result.is_ok(),
        "{} should have succeeded: {:?}",
        desc,
        result.err()
    );

    let molecule = result.unwrap();
    assert!(
        !has_nonstandard_features(&molecule),
        "{} should not have query features",
        desc
    );

    assert_eq!(molecule.atom_count(), 1, "{} should have 1 atom", desc);
    assert_eq!(molecule.bond_count(), 0, "{} should have 0 bonds", desc);
}

#[rstest]
#[case(b"Ethane\nRDKit          3D\nGenerated by RDKit\n  2  1  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.5400    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0  0  0  0\nM  END\n",
      "standard ethane")]
fn test_parse_mol(#[case] mol_str: &[u8], #[case] desc: &str) {
    let result = parse_mol(mol_str);
    assert!(
        result.is_ok(),
        "{} should have succeeded: {:?}",
        desc,
        result.err()
    );

    let molecule = result.unwrap();
    assert_eq!(molecule.atom_count(), 2, "{} should have 2 atoms", desc);
    assert_eq!(molecule.bond_count(), 1, "{} should have 1 bond", desc);
}

#[test]
fn test_parse_mol_query() {
    // MOL with query atom 'A' (any atom)
    let query_mol = b"Query\nRDKit          3D\nWith query atom\n  1  0  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0\nM  END\n";

    let result = parse_mol(query_mol);
    assert!(
        result.is_err(),
        "Standard parser should fail on query atoms"
    );

    let error = result.unwrap_err();
    let error_string = format!("{}", error);
    assert!(
        error_string.contains("MOL parsing failed")
            || error_string.contains("Standard MOL parsing failed"),
        "Error should mention parsing failure: {}",
        error_string
    );
}
