[package]
name = "umol-io-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
libfuzzer-sys = "0.4"
umol-ast = { path = "../../umol-ast" }

[dependencies.umol-io]
path = ".."

[[bin]]
name = "fuzz_parse_opensmiles"
path = "fuzz_targets/fuzz_parse_opensmiles.rs"
test = false
doc = false
bench = false
